### ISSUE TITLE
LGPL violation/Missing references to ethereumj project

### ISSUE THREAD

**Issue by freddy36** [tronprotocol/java-tron#25] opened 2017-12-31 13:03 UTC
It's very obvious that java-tron is based on the ethereumj project.
E.g. compare these two files (Just a random example out of many):
https://github.com/tronprotocol/java-tron/blob/develop/src/main/java/org/tron/datasource/leveldb/LevelDbDataSource.java
https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/datasource/leveldb/LevelDbDataSource.java

AFAIK this is violation of the LGPL (ethereumj) license because you didn't mention that java-tron has been derived from the ethereumj project.

You might want to get your licensing right. Copying someones work without giving them proper credits  is at leased considered very bad practice in the open source community (ignoring any legal aspects of this because I'm not a lawyer).

**Comment by tronfoundation** [comment] 2018-01-02 04:11
We referred some codes of ETH due to the festinate time, we apologize for it and will correct it immediately.

**Comment by tahitithebob** [comment] 2018-01-11 01:26
And you just moved the file and changed some properties:
https://github.com/tronprotocol/java-tron/blob/8e64485be80755de4f81ba472152777eb21f1131/src/main/java/org/tron/storage/leveldb/LevelDbDataSourceImpl.java

This is not cool!

**Comment by pornin** [comment] 2018-01-11 20:29
Also, files from https://github.com/tronprotocol/java-tron/tree/develop/src/main/java/org/tron/crypto/cryptohash appear to be straightforward imports from sphlib ( http://www.saphir2.com/sphlib/ ), with just the license removed and replaced with their own. Given that the sphlib license is very permissive and would see no problem with the import, provided that "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software" (exact wording of the license text), I'd say that this license surgery is quite inelegant. This is not the behaviour of worthy developers.

**Comment by e-sushi** [comment] 2018-01-12 02:14
_When you get mauled by a bear, you know you've messed up badly._

@tronfoundation Congratulations on losing your overall credibility and general public image. By bluntly stealing code and claiming it to be yours, you've done more that ignoring international copyright laws and violating every single license involved. Way to go… has been a long time since I saw such an innovative way to kill a project's public image beyond the point of recovery.

**Comment by danrcarter** [comment] 2018-01-12 02:42
Is this FUD?

Cheers,

Dan Carter
Founder | Director
p. 1 888 401 6668
w. cleanthecreek.com
e. dan@cleanthecreek.com

Clean the Creek - Leave it better than you found it.

**Comment by e-sushi** [comment] 2018-01-12 02:48
@danrcarter Nope, it's a FACT. (You can practically verify these reports all by yourself, just like I did.)

**Comment by danrcarter** [comment] 2018-01-12 03:02
Did you use a file compare to how did you verify just curious can you point us To the code. What other libraries are being used just wanna confirm this because we really like the Tron project and I’ve been actually working really hard on the contributing.

Cheers,

Dan Carter
CEO | Systems Analyst/Designer
p. 1 888 401 6668
w. redcherry.ca
e. dan@redcherry.ca

Red Cherry Digital Experience.

Proud to be recognized as one of Canada’s Top Web Design Firms for 2015.

**Comment by e-sushi** [comment] 2018-01-12 03:18
@danrcarter 

In case of doubt, follow the mentioned links and do your homework by comparing things. Being a _"Founder | Director | CEO | Systems Analyst/Designer"_ it shouldn't be hard to do that as it should be part of your knowledge range when you are _"actually working really hard on the contributing."_

As for your _"What other libraries are being used…"_ question, I'll bluntly remind you that I am not being payed for a full code analysis. You're free to do that yourself as part of your _"contribution"_ efforts. Besides, should I decide to dive into a full code analysis, you can be sure I'll be reporting alioke findings to the involved copyright owners as that's the correct thing to do. Somewhat like one reports infosec findings to those involved instead of sharing it with the general public in some comment area. 'enough said.

**Comment by danrcarter** [comment] 2018-01-12 03:23
@e-sushi we havent noticed this and I am not the one working on the project simply managing it. Really don't get angry at me we are trying to build a platform for Clean the Creek off of TRON which exists in both App stores for free and we did'nt get paid for either we built for the better of the earth. Man you come out guns ablazing

**Comment by e-sushi** [comment] 2018-01-12 03:27
@danrcarter Please don't get me wrong. I'm neither angry, nor emotional in any other way. I'm merely pointing out the obvious.

**Comment by danrcarter** [comment] 2018-01-12 03:28
@e-sushi I appreciate that

**Comment by e-sushi** [comment] 2018-01-12 09:31
@danrcarter Since you deleted most your comments from our exchange, you might as well delete the last ones too.

**Comment by e-sushi** [comment] 2018-01-12 09:34
@danrcarter Since you deleted most your comments from our exchange, you might as well delete the last ones too. Doesn't make much sense to keep out-of-context messages you've meanwhile edited just to promote your app. (Where I come from, we call that link-spam.)

**Comment by AngelQuirogaM** [comment] 2018-01-12 09:41
I have been reading this thread in my email. Just take it easy for all please :)

For all not so constructive comments:
- let the project developers breath a little bit please, and check it in the next release not at every commit.

For the developers:
- all the comunity is watching you, please kill all legal doubts about this in the next release.

Have a good day

**Comment by tronfoundation** [comment] 2018-01-14 16:10
# official statement
**The design of TRON is based on it's own system and the realization of codes, some codes of Ethreum were used as reference, we didn't note related license, from now on we will note the copyright ownership and promise this won't happen again. Thank you for your support.**

**Comment by UseCoin** [comment] 2018-01-15 01:06
@tronfoundation you fucking idiots

**Comment by larryluckland** [comment] 2018-01-15 01:37
So all these _Senior_ Alibaba engineers are just copying and pasting code? So much for Justin Sun and his "very strong developer team from great companies."

**Comment by penrique** [comment] 2018-01-15 01:50
@larryluckland ever coded? copy paste is THE most powerful tool for any developer, thing is to know what to do with it afterwards. 95% of crypto is copy pasted code, however they should have left licenses untouched.

**Comment by ALawliet** [comment] 2018-01-15 02:26
in on this because i wanna be a part of history. cheers everyone.

**Comment by ac-opensource** [comment] 2018-01-15 03:11
People are complaining about this like this is released already. It's not even "released" yet so no actual violation was committed.

**Comment by nanilab** [comment] 2018-01-15 04:24
Not the first time TRON Protocol does this...

**Comment by KyleHunter** [comment] 2018-01-15 04:29
@ac-opensource
Yes, but they have made significant monetary gains because of this premise.

**Comment by nurazhar** [comment] 2018-01-15 05:03
isn't tron a blockchain based in China?

**Comment by ovived** [comment] 2018-01-15 05:07
why is this a surprise.. this is how the Chinese do business. lol DUMP TRON

**Comment by kalittl** [comment] 2018-01-15 05:09
I agree with you Andrew!  These idiots think they uncovered something new about open repos on github.  Here’s a bomb shell story for the fake detective folks https://m.slashdot.org/story/334037

LOL

**Comment by lxwagn** [comment] 2018-01-15 05:09
This issue has been fixed as of commit [2754bcb51c4d51191e2b2c89346b76eff29e0ed3](https://github.com/tronprotocol/java-tron/commit/2754bcb51c4d51191e2b2c89346b76eff29e0ed3). 

Please close the issue.

**Comment by ovived** [comment] 2018-01-15 05:19
amateur hour.. bulgarian coders copy pasting and removing licensing lol

**Comment by rmittapalliz** [comment] 2018-01-15 05:31
Okay everyone just relax. copy paste not bad. But be open about it and give credit to ETH. @tronfoundation There is nothing wrong that your devlopers copy paste the code . if it helps tron to move forward by copy paste its definitely not a bad idea since it saves time. just dont forget to give credit.

i think people needs to stay away from development team and relax. 

Copy pasting whitepaper is not cool tho.

**Comment by patthekenny** [comment] 2018-01-15 05:42
What's the point of free software if developers won't follow the licenses anyway?

**Comment by oferze** [comment] 2018-01-15 05:46
A crucial mistake in your official statement:

its, not it's.

**Comment by bonesoul** [comment] 2018-01-15 05:51
Copy & paste the whitepaper, then copy & paste the sources. That's what we call TRON.

**Comment by YuurinBee** [comment] 2018-01-15 06:00
Not to mention in your "official statement", you cannot even spell Ethereum correctly. You copy and pasted code, there's no reason you can't copy and paste the name, too... smh

**Comment by georgemickael-b** [comment] 2018-01-15 06:04
For those who are whining about this issue. All these issues are common in development. If you say it's not, you haven't worked on serious projects with so much pressure to deliver. The thing hasn't even been released, its not even a violation now.

You are not going to perfect on day 1. This is professional network, don't undervalue yourself by making fake profiles and/or posting inappropriate comments.

**Comment by rmittapalliz** [comment] 2018-01-15 06:05
Just shill people it's not issue at all

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by opuxilem-4055** [comment] 2018-01-15 06:17
Protip: buy more when the price crashes super low!

**Comment by rome138** [comment] 2018-01-15 06:23
Maybe it is commented out lol

**Comment by pyskell** [comment] 2018-01-15 06:23
GPL covers whenever code is distributed. Even if not "released" it was still distributed on GitHub.

Additionally the first thing the copyright holder does is ask for proper licensing and attribution.

The disturbing/garbage part is that removing those copyright notices and find/replace ethereum -> tron DOESN'T happen by accident. This is the second incident after the whitepaper. A third will be a really serious pattern.

**Comment by myrual** [comment] 2018-01-15 07:35
in on this because i wanna be a part of history. cheers everyone.

**Comment by Mardoxx** [comment] 2018-01-15 07:46
Has anyone called the cyberpolice?

**Comment by dreday966** [comment] 2018-01-15 07:46
Blockchain world rule 1: be honest and transparent.

**Comment by MagicalTux** [comment] 2018-01-15 08:01
AFAIK LGPL requires only to re-license under the same LGPL license (which [java-tron is](https://github.com/tronprotocol/java-tron/blob/develop/LICENSE)) so t here is no LGPL violation here.

Removing the copyright header & details of the source is however be in violation of copyright laws of most/all jurisdictions (the "Copyright (c) [2016] [ <ether.camp> ]" part).

**Comment by skibz** [comment] 2018-01-15 08:15
when the ethereumj project was originally licensed, it was using the [MIT license](https://github.com/ethereum/ethereumj/commit/7475c7bbe56c27ca7f89655054398ee9f03fe6fd#diff-9879d6db96fd29134fc802214163b95a). what does this mean for projects that derived from it at that point in time? are they also subject to the new license now?

**Comment by andydj** [comment] 2018-01-15 08:43
@skibz no because you can't re-licence already-released code - it's not retrospective. It applies to all code released subsequent to the point of the license change. You can't legally back-port updates to the LGPL code to the old MIT licensed codebase, unless it's de minimis (trivial amounts).

Changing the license at the top of the code (and nothing much else) is simply a violation of international copyright law. Doesn't require any particular license, unless the existing license explicitly allows you to do this, or the work is already in the public domain or copyright has expired.

**Comment by diagprov** [comment] 2018-01-15 09:18
Issue has not been fixed as of 2754bcb51c4d51191e2b2c89346b76eff29e0ed3, in particular the sphlib license has not been added to the affected files.

I have not checked to see if any other stolen code exists and whether the license has been replaced.

**Comment by canhlinh** [comment] 2018-01-15 09:19
Oh my money.
I had reviewed this source code before i invested my money to TRON.
I've complained to my friends that `The code are not so good. We should not invest to TRON.` 
But they said `Developers from China are very good. This project is just a draft. The core was written by C++ and not published yet.` Then I FOMO and keep believe developers from China.
Please go ahead and get back my trust.

**Comment by githubbrunob** [comment] 2018-01-15 09:34
who cares about giving credits to a, b or c? Intelectual Property is crap!
and if that is really required by the lamer-community, then I would lose time on the references only when the product is out AND successful. meanwhile, we have to learn how to live in a copy-paste world. we can't have closed-source because otherwise no one would believe our product, so we really have to be fast, copy-pasting existing solutions (Ethereumj, Status, FileCoin, Flixxo, BAT) to come up with a wide-range product, tested and reliable for the users to use.

**Comment by andydj** [comment] 2018-01-15 09:35
As mentioned by others above, if it's on GitHub it HAS been released AND Distributed, as defined by the LGPL. If it's publicly availabile, it has been RELEASED, and is thus in violation.

NOW IS THE TIME TO FIX this, not "the next release". Every commit to or clone/download of an LGPL covered source file is further violation. Hate to seem whiny, but that's just how it is, like it or not.

**Comment by andydj** [comment] 2018-01-15 09:41
@githubbrunob you'll soon change your tune if the repo gets pulled from GitHub due to a copyright claim - then nobody gets to clone it anymore. Copyleft and permissive licenses rely on turning the exiting copyright system back on itself, to provide freedom for all. I agree the term "Intellectual Property" is crap, this is the way we get change for the better - by using the system against itself. The idea is that as many people as possible benefit, not just the few who make money off the efforts of other people.

**Comment by githubbrunob** [comment] 2018-01-15 09:42
@andydj if the repo gets pulled from GitHub for whatever reason, that only means one thing: censorship.

**Comment by andydj** [comment] 2018-01-15 09:48
It wouln't mean censorship per se. It would mean github avoiding being sued as an accessory to copyright infringement. It's how the safe harbour rules work: any infringement must be removed upon notification, or the outlet basically becomes liable. This is why youtube/facebook/soundcloud etc. all have takedown procedures - they can't continue to exist with the constant threat of lawsuits. Even if you idealogically oppose these ideas (as I do) you have to accept that you have to play by the rules of the existing system, whilst pushing the boudaries, in order to survive.

**Comment by Fohdeesha** [comment] 2018-01-15 09:49
Censorship? No, it means GitHub enforcing their TOS as they always have. It quite clearly says they will not host stolen code (which, as defined by their TOS, and the gpl license in general, includes code that has been reused with licensing terms and origin removed)

**Comment by airwave-development** [comment] 2018-01-15 09:50
It is copyright infringement. I already did an article on tron https://medium.com/@olivierdejong/overvalued-meets-undervalued-71003a5b9dae. And now it turns out that the code that is available here is copy and paste.. Sad..

**Comment by githubbrunob** [comment] 2018-01-15 09:59
@Fohdeesha how do you prove it is stolen code when we have automated code generators that also print those useless comments about copyright bla-bla-bla...? "Stolen code" that's a very amusing concept.

**Comment by Fohdeesha** [comment] 2018-01-15 10:05
it's not a "concept", it's defined very clearly by the GPL terms. When you take someone's licensed code, (which Tron officially admitted doing above), remove the license terms and identifier, and do not mention the source (which once again, tron admitted to doing above) that is defined as stolen, by both gpl terms and githubs own TOS. Are you new to software development? This is beginner level stuff, I wouldn't have been caught dead doing this even when I was starting out in highschool

**Comment by andydj** [comment] 2018-01-15 10:14
@githubbrunob you seem not to get that a simple, free, easy, and POLITE solution is to just follow the licensing requirements of each upstream project. It's not even hard.

You are right that it's not "stolen code" - it's copright infringement. Code cannot be "stolen" as far as the law is concerned (because the original owner still has their copy - theft involves removing the item from the possession of the original owner) but copyright infringement law does have drastically costly implications - not only lawsuits, but incredibly expensive standard fines. It's meant to be a deterrent, and that, it certainly is. Just see how the system has dealt with previous companies that have flouted the rules... Pirate Bay, MegaUploads, Napster... to name a few.

But with copyleft software, it doesn't need to end in destruction: just follow the license, and CARRY ON AS BEFORE in all other respects. It doesn't stop you doing much, if anything other than abiding by the license terms. And it's better for everyone. Check out http://gpl-violations.org/ for a rolling history of the afaik 100% success record against violations of the *GPL licenses.

**Comment by githubbrunob** [comment] 2018-01-15 10:17
my question is: why matter with licensing, and references and all, if no one profits if someone references your code?

I understand github's problems with law enforcement. but then I feel coders are working for the lawyers, and not for the community. next question: when does/will github goes decentralized?

**Comment by githubbrunob** [comment] 2018-01-15 10:20
@Fohdeesha I'm still in kindergarten, I just don't take anything for granted.

**Comment by andydj** [comment] 2018-01-15 10:23
It's precisely because of FREEDOM - freedom of the USERS of the code to run,study,share,modify the code without others encumbering it with additional restrictions. Everybody gets to have the same rights all the way down the line. Without this guarantee, someone, somewhen, will try to take them away.

It's a reciprocal deal. You get access to the code and everybody else gets access to your improvements, if you choose to share them. You can of course keep them to yourself, but AS SOON AS YOU GIVE SOMEONE ELSE YOUR "IMPROVED" VERSION, YOU HAVE TO PROVIDE THE SOURCE CODE TOO. Fork as much as you like, but play by the rules. It keeps everybody (apart from the shady suits) happy.

**Comment by githubbrunob** [comment] 2018-01-15 10:27
@andydj code is not even digitally signed as it should be with PGP keys of the developer. Licencing is just a meaningless comment on the header of the file. People can copy the files, change it as they please while leaving the header untouched. Means nothing. Toilet paper is a better invention.

**Comment by andydj** [comment] 2018-01-15 10:33
@githubbrunob Haha. Why should PGP even be involved? It's proprietary, and flawed. I'm afraid practically the whole internet disagrees with you anyway. Without it, the internet wouldn't even exist. Doesn't really matter what you think if the whole world disagrees with you. Of course, you can act according to your own views. Good luck with that.

**Comment by cmhsu-cs** [comment] 2018-01-15 10:35
lmao

**Comment by ernesthilvano** [comment] 2018-01-15 10:51
Man, THIS IS OPENSOURCE, why hate having no copyright? tsk tsk.

**Comment by airwave-development** [comment] 2018-01-15 11:04
The thing is this. Tron is a very hyped erc20 coin. The market value right now is 4 billion bucks and the team should have enough funds to develop something special. It is really weird that a team with access to this amount of money does not have anything substantial in their repositories. The people behind TRON say that they have a lot of development capacity. This repository says otherwise. The code in this repo can be made by one single person within a short timespan. 

What makes it even worse is that large parts of the code in this repository has been COPIED without giving credits to the original developers and without saying that this code has been COPIED. This will give a false impression to any person, let alone investor, that there is some heavy coding going on. A big red flag. I really hope that the general public will pick up on this. There are a lot people who have invested their savings in this and they should know that these practices are taking place

**Comment by JohnnyQQQQ** [comment] 2018-01-15 11:19
The cryptohash directory could be replaced by an import of https://github.com/sfuhrm/saphir-hash

**Comment by Dustymcp** [comment] 2018-01-15 11:20
Copy pasting is ok but atleast keep the licenses, if you are using code from anywhere you dont fuck with the license!

**Comment by Avamander** [comment] 2018-01-15 11:39
I'd love to see the repo hit with a DCMA.

**Comment by tomsej** [comment] 2018-01-15 12:08
Ok, guys, too much drama here. First version of tron-java was published on Github about 27 days ago and license was added in this commit - https://github.com/tronprotocol/java-tron/commit/af167ac892170c839a4394f578a95c53576ad487#diff-472a6d957e5426d4236721b013050c53. It is definitely auto-generated by IDE and probably some junior developer. Yes, it is not professional (and a lot of repos on Github are doing same mistake), but you know - it happens.

**Comment by airwave-development** [comment] 2018-01-15 12:15
Yes it happens. But your are forgetting that this is not just some hobby project. It is pathetic to see that the only thing here is this repo. It is a $4 BILLION project...

**Comment by mag0x** [comment] 2018-01-15 12:31
is this the first time code has been stolen like this

**Comment by nukec** [comment] 2018-01-15 12:55
no fud, no drama. more fud, more drama = more exposure to tron. it's ok as long as they deliver

**Comment by philiparthurmoore** [comment] 2018-01-15 13:04
If the original problem raised in #25 has been fixed, this thread needs to be closed. If it has not been fixed, this thread needs to remain open and fixed.

GitHub is not a place to air your bag HODLing grievances. It's a place to raise legitimate code issues. Please, for the love of god, go back to Twitter with the nonsense.

Questions:

1. @tronfoundation Has this issue been resolved?
2. If not, when can we expect a resolution?
3. Are there any other code repositories you're working on that are private or is this the official repository that we should be viewing to keep up with your work?
4. Can you give us a little more guidance about who the primary developers are for this project so that they can weigh in and make corrections?

Thanks.

**Comment by ruchern** [comment] 2018-01-15 13:18
@philiparthurmoore the best reply of the whole thread.

**Comment by zealthio** [comment] 2018-01-15 13:24
@philiparthurmoore I second that. Leave it on twitter or Reddit BITCHES! They said sorry, wont happen again. Let them get on with the job.

**Comment by bulrush15** [comment] 2018-01-15 13:26
Developer here. @georgemickael-b  wholesale copying of licensed software, even open source software, without abiding by the license is not common where I'm from in the US. Maybe in India or China yes, but not in the US.

**Comment by githubbrunob** [comment] 2018-01-15 13:33
@bulrush15 maybe they want to evolve the libraries, and therefore liability (e.g., in case of failure) should not go to the original authors.

**Comment by georgemickael-b** [comment] 2018-01-15 13:46
@bulrush15  Sorry about you stereotypes.  While you are thinking baselessly that following license is based on geography , my emphasis was , it is inevitable. If you had built/building an company and not working for a company , you would know this.
My point was to , get over the issue. Stop crying and focus on next milestone. You are not going to get everything right the first day.
This section is for reporting issues and getting to solve it. Not a platform for personal/racist 
criticism. Be and act professional.

**Comment by fragamemnon** [comment] 2018-01-15 13:58
Ther's nothing personal and nothing racist about his statement.

Even your example of starting up your own company is not applicable, since we are talking about a project worth _billions_.

**Comment by Namzhil** [comment] 2018-01-15 14:05
weak shit.

**Comment by lostick** [comment] 2018-01-15 14:13
awful thread, but what do you expect from blockchain devs who copy/paste code and remove licenses really...

**Comment by airwave-development** [comment] 2018-01-15 14:28
It says is enough that nobody of the supposed "40 devs" made the effort to reply to this thread......

**Comment by SparK-Cruz** [comment] 2018-01-15 14:32
Intelectual property is bullshit, good evening.

**Comment by jtreal** [comment] 2018-01-15 15:11
Removing the license took time so any defence of this act stating they lacked time is just baloney. Forget copyright etc.. The problem is they are taking credit for other people's work and trying to cover it up.

**Comment by joem789** [comment] 2018-01-15 16:48
Too many people born into entitlement thinking they own their own ideas. To you copying is stealing. To others copying is reproducing something to learn from it. When an American copies a software program it becomes "reverse engineering" for some reason. I think all you lurkers should stay off here and let work get done peacefully. Try Googling China and Plagiarism and learn something about a culture that's not your own. Maybe then you will understand what is really happening here. Either you can be supportive or sit around and whine about things not suiting your ideas. Leave them alone. There are plenty of developers here who are being supportive and volunteering their time and efforts. Nobody needs you complainers here slowing down progress. The obstacles that are in place can be and will be overcome with a little more time. Give it a chance.

**Comment by ruchern** [comment] 2018-01-15 18:02
This thread has gone way off topic and off the actual purpose of an issue on Github. The collaborators or owner of this repo should just lock and limit the conversation to the contributors for quality discussion.

**Comment by ahivarn** [comment] 2018-01-15 18:11
So many major coins are forks of Bitcoin or similar currencies. That's open-source philosophy. Only issue here is the lack of attribution to proper sources.

The biggest issue with Tron is the excessive dumping happening as showing in Ether scan. Can @tronfoundation explain what's actually happening with people dumping hundreds of millions of coin at once

**Comment by Gomachi** [comment] 2018-01-15 18:14
@joem789 Your statements and "arguments" sound like a string of horrid jokes. I know you hold a sizeable amount of their shit tokens, but come on. If you're going to make an attempt at an argument, as least make it slightly reasonable and involving less straight up stupidity.

> Too many people born into entitlement thinking they own their own ideas. To you copying is stealing. To others copying is reproducing something to learn from it. When an American copies a software program it becomes "reverse engineering" for some reason.

Apparently, you have no idea what 'copying' means in this context. First of all, we're not dealing with ideas here. Ethereum is an IMPLEMENTATION of an idea, not an idea. There's a difference between stealing an implementation (literally copy/paste source code) vs copying an idea. H.U.G.E .. DIFFERENCE. There's a reason why there are things called patents, intellectual property, and billions of dollars in IP lawsuits every year by companies. 

If your "logic" was true, every company would be stealing from each other blatantly and indiscriminately, and nothing could be done. 

The 'copying' you are trying to (and fail) to refer to is when a company sees a product that is gaining a lot of traction, and says "hey, we could create a product with pretty much the same features. Let's do it." Ahem, Instagram Stories features being derived from Snapchat. 

It has absolutely nothing to do with "I'm just going to copy and paste code from some other codebase and claim it as my own. Herpa Derp."

> Try Googling China and Plagiarism and learn something about a culture that's not your own. Maybe then you will understand what is really happening here. 

Are ... you seriously trying to justify this by pulling some kind of nonsensical "culture" card? 

"Let them be! It's their culture! Learn more about their culture of plagiaristic culture and you'll then respect what the Tron team has done." 

Whether or not plagiarism itself is rampant throughout China, you talk about it as if it's something that's good and should be revered. Wat?

> Nobody needs you complainers here slowing down progress. 

When that progress is copy/pasta code from other codebases and claiming it as your own, you better bet you butt people are going to complain.

> The obstacles that are in place can be and will be overcome with a little more time. Give it a chance.

What? Do you stray onto a different topic? It sounds like you're now addressing people who are pissed about ... slow development time? I don't see how this has anything to do with anything that was stated prior.

**Comment by joem789** [comment] 2018-01-15 18:44
I guarantee your grandmother copied a recipe from a book and called it her own. Her special touches made it her own. But still copied nevertheless. When 3M company glue patent ran out, many companies copied it to make innovative products better than 3M! That's innovation in the name of plagiarism! It's all in how you look at it. Furthermore. It amazes me at how many people cry plagiarism in an open source community. Sounds pretty hypocritical. I am an American. And the first to admit our society is one of a sense of entitlement where we get to own ideas. Which is worthy of a joke. Because you cannot own intelligence. I grew up copying everything everyone did to get good at adapting and overcoming challenges. If people had hovered around me during that time, they would have been complaining cause I stole their ideas. Can anyone prove that Alibaba wasn't plagiarized to become the product it is? Why not? After all, Asia seems to copy everything. And somehow, they still dominate the world with their products. Products that YOU are thankful for every day because of the cheap prices. 

I personally see this TRON project as something more than coding and crypto dogs. I see it as a collaboration between East and West and a chance to tear down cultural carriers that exist. Finding a new common ground. But this isn't about Asia assimilating to American culture. It is about both sides re-evaluating their beliefs. There's a helluva lot that needs to change just on the American side.

**Comment by jtreal** [comment] 2018-01-15 19:27
@joem789 professional developers see through that poor attempt at a strawman fallacy. This is just a slap on the wrist but it seems to be exposing awful ethics and a lot of red flags. **Then again Alibaba is a copy of ebay/amazon lest we forget so who is really surprised by this behaviour.**

**Comment by kemargrant** [comment] 2018-01-15 19:43
![200](https://user-images.githubusercontent.com/2120365/34959011-ed060b70-fa66-11e7-9cc7-26a59cc9c2b7.gif)

**Comment by dylanorgeron** [comment] 2018-01-15 21:42
put me in the screencap

**Comment by ac-opensource** [comment] 2018-01-16 09:25
@wongjustin99 Submitted a fix: https://github.com/tronprotocol/java-tron/pull/65

**Comment by jessereitsma** [comment] 2018-01-16 12:57
> **@joem789**
> I guarantee your grandmother copied a recipe from a book and called it her own.

But she never publicly "released" it under her own name, does she?

**Comment by jameslouiz** [comment] 2018-01-17 10:59
I think people are missing the point and saying its okay to copy code. The main point is they have _lied_ about it and tried to cover it up which raises more questions about the legitimacy of the project and the capability of the team. 

What other shady tactics are happening that we _can't_ see?

**Closed** 2018-03-12 17:09 UTC

**Comment by bohemianaman** [comment] 2018-06-14 10:41
Never expected this from TRON

**Comment by Abiraminfo** [comment] 2018-06-20 02:55
Bidu a successful Chinese search engine company is a copy of Google. 
QQ Chinese social networking company is a copy of Facebook.
Huawei is a successful Chinese copycat of Cisco .
Xiomi is a successful Chinese copycat of iPhone .
Wechat is a Chinese copycat of WhatsApp.
Alibaba itself is an extremely successful copycat of eBay . 

So being a Chinese copycat could as well means success. China doesn't allow foregin companies taking strong root within it's borders. If China wants to allow a crypto currency to operate in China, it might as well be TRON ! Don't be surprised, it's a huge market on it's own and copyright doesn't matter there 😂

**Comment by bdm123** [comment] 2018-06-20 03:44
Copying and stealing code is different than copying a business model. 

What a shit show this is going to be.  Good luck on the grenade launch.  LOL  😂

**Comment by ruchern** [comment] 2018-06-20 05:04
@tronfoundation I think this issue should be locked and limited to members and collaborators only.
