### ISSUE TITLE
MISTAKE - FAIL-TIMEOUT FOR CONTRACT EXECUTION

### ISSUE THREAD

**Issue by Lobzzzz** [tronprotocol/java-tron#3843] opened 2021-06-12 10:38 UTC
### 1. What did you do?
There was an error in a REV transfer. The txid is: 6d7ce540491eb18d7300ae9c99f380cc4bf7b3725018535022f467a3afe66355

### 2. What did you expect to see?

Hope to return a coins back

### 3. What did you see instead?

Hello. I often transfer so Rev coins and has always been fine. But the last transaction came out with a mistake (FAIL-TIMEOUT FOR CONTRACT EXECUTION), what should I do to return the money? I do not understand where these coins are now, maybe they are due to the mistake already returned to you on Kucoin's wallet, but not on my personal stock exchange?

https://tronscan.org/#/transaction/6d7ce540491eb18d7300ae9c99f380cc4bf7b3725018535022f467a3afe66355

**Comment by boromand** [comment] 2021-06-12 11:05
Hello, how should I get our coins back? Help my sister or give me an
address so that I can send my wallet address to get my coins back.

در تاریخ شنبه ۱۲ ژوئن ۲۰۲۱،‏ ۱۵:۰۹ Lobzzzz ***@***.***> نوشت:

**Comment by Lobzzzz** [comment] 2021-06-12 11:18
What? Do you want the address of my wallet to which I need to return the coins?

**Comment by lazike66** [comment] 2021-06-13 15:49
Like

**Comment by Benson0224** [comment] 2021-06-16 05:22
You will not lose your token if the transaction failed, it is still in your wallet. 

Please check more info on why time out from here: https://developers.tron.network/docs/faq#2-why-would-i-trigger-out_of_time-error-when-calling-contract-function

**Comment by Lobzzzz** [comment] 2021-06-16 08:59
> You will not lose your token if the transaction failed, it is still in your wallet.
> 
> Please check more info on why time out from here: https://developers.tron.network/docs/faq#2-why-would-i-trigger-out_of_time-error-when-calling-contract-function

Thanks for the info. I will close the ticket when the exchange returns the money to me.

**Comment by lazike66** [comment] 2021-06-21 14:34
Great

**Comment by Benson0224** [comment] 2021-06-22 07:35
Thanks for your contribution to java-tron. 
This issue will be closed as the issue is already solved. 
Please feel free to re-open this issue if you still see it, thanks.

**Closed by Benson0224** 2021-06-22 07:35 UTC

**Comment by peacebd** [comment] 2021-07-14 05:46
Thanks

**Comment by Mgholami436** [comment] 2021-10-31 13:05
> > Thanks a lot for your help and kindness. I hope kucoin return my token back is soon as possible. Best wishes
> 
> Yes, don't worry, everything will be fine. You just have to wait)

Hell Dear, 10 days has passed I emailed to kucoin still waiting no answer from Kucoin yet!!! :((( how long it took to you Kucoin answered your email?? Is there any other ways to contact to Kucoin??

**Comment by michelcrypt4d4mus** [comment] 2023-10-03 05:22
> TGv6iqKwZK1xDbfuYdcQqCrAGwRQMSUVpr

Кому принадлежит этот кошелек? KuCoin?
