### ISSUE TITLE
SolidityNode has an Uncaught exception

### ISSUE THREAD

**Issue by wangzichichi** [tronprotocol/java-tron#978] opened 2018-06-11 03:03 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
SolidityNode on the env,  "47.93.9.236:18897"

2. What did you expect to see?
No exception

3. What did you see instead?
On July 8, I found an error log on this SolidityNode.
11:53:51.459 ERROR [Logback shutdown hook [default]] [general](DefaultConfig.java:26) Uncaught exception
java.lang.NoClassDefFoundError: ch/qos/logback/core/LifeCycleManager
  at ch.qos.logback.core.ContextBase.getLifeCycleManager(ContextBase.java:260)

**Comment by wangzichichi** [comment] 2018-06-11 03:03
This issue has report to the engineer taihaofu

**Comment by taihaofu** [comment] 2018-06-12 09:49
Hard to reproduce. And as far as I see from the log, it happened when we trying to kill solidityNode thread. Since it only happened once , my suggestion is to wait and see if it occurs occasionally or not. 
You can close it and feel free to reopen it if necessary.

Thanks.

**Closed** 2019-06-13 02:59 UTC
