### ISSUE TITLE
Tron node was slow to catch up

### ISSUE THREAD

**Issue by ksiezak** [tronprotocol/java-tron#5016] opened 2023-02-22 12:15 UTC
Hello,
for some reasons I was forced to shut down a fully synchronized node for about 48h. When I restarted it, it downloaded the blocks in about 11h to catch up with the blockchain.

My expectation was that such a short shutdown time should not cause catch-up longer than approx. 15 minutes, or at worst, about one hour.

The machine was not significantly loaded during the catch-up.

Here are specifications:
HP ProLiant DL380 Gen9
2x Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
LXC container with 16 CPU threads, 32GB RAM, storage is ZFS RAIDZ array of 3 Samsungs Pro 860 4TB.
Internet connection is:
Download: 644.69 Mbit/s
Upload: 511.87 Mbit/s

OS: Proxmox 7.3
OS in LXC: Debian Bullseye
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)

Starting command: java -Xmx24g -XX:+UseConcMarkSweepGC -jar /opt/tron/FullNode.jar -c /opt/tron/main_net_config.conf --es --log-config /opt/tron/logback.xml

Any clues or suggestions? How long it should take? Maybe my expectations are wrong?

**Comment by halibobo1205** [comment] 2023-02-22 15:23
According to your current machine and startup script, it takes about 6.5 hours, 11 hours is not really normal. Would you like to try using [arthas](https://arthas.aliyun.com/en/doc/quick-start.html) to help find the problem? When attach to `java-tron` Java process, you can use [trace](https://arthas.aliyun.com/en/doc/trace.html#start-demo) `trace org.tron.core.db.Manager processBlock` to find the problem.

**Comment by lurais** [comment] 2023-02-24 03:19
@ksiezak hello, can you provide more info about the running state, such as the tron.log? Or you can just try to restart it without the param --es and check the problem.

**Comment by ksiezak** [comment] 2023-03-01 13:23
@halibobo1205 I will have similar situation soon because I will be migrating to RAID10. I will try to use arthas then.

@lurais do you want logs from now or from synchronization period?

**Comment by lurais** [comment] 2023-03-02 08:45
@ksiezak hello , from synchronization period is ok.

**Comment by ksiezak** [comment] 2023-03-13 14:34
I managed to take another test and gather some data.

Changes:
- Updated node from v4.7.0.1 to v4.7.1
- Added one more Samsung Pro 860 4TB
- ZFS pool type changed from RAIDZ1 to RAID10

Test, results and expectations:
- 41,5h downtime
- 7,5h catching up again
- if speed was the same as in the first situation it should take 9,5h to catch up from 41,5h downtime, but about 5,6h if @halibobo1205 assumptions are correct

I took arthas logs about 15 minutes after node started to synchronizing again. Speed was quite steady.
arthas log: https://pastebin.com/2Q7JVQV1
arthas results: https://pastebin.com/3KhpLx0g

I unfortunately don't have logs from Tron itself from synchronization period because I only keep them for 7 days. I can provide you with logs from synchronized node if they will be any help.

**Comment by lurais** [comment] 2023-03-14 11:26
@ksiezak it seems to be clear that process transaction take most of time rid of the validate sign operation ,and to analynize the root cause ,you can use [trace](https://arthas.aliyun.com/en/doc/trace.html#start-demo) trace -E org.tron.core.store.AccountStore|org.tron.core.db.Manager get|processTransaction to get more detail info, what's more, you can use arthas to collect the profiler info before and after the update to find something useful(ref:https://arthas.aliyun.com/doc/profiler.html)

**Comment by ksiezak** [comment] 2023-03-22 08:36
@lurais I collected requested info. I ran profiler only for recent version because I don't want to downgrade my node or shut it down unnecessarily.

Trace log: https://pastebin.com/xXe1Q89S
Trace results: https://pastebin.com/1NPbyybF
Profiler http report: https://ufile.io/75yro3jl

**Comment by lurais** [comment] 2023-03-22 10:09
> @lurais I collected requested info. I ran profiler only for recent version because I don't want to downgrade my node or shut it down unnecessarily.
> 
> Trace log: https://pastebin.com/xXe1Q89S Trace results: https://pastebin.com/1NPbyybF Profiler http report: https://ufile.io/75yro3jl
@ksiezak hello ,this profiler file seems can not be open in my computer normally( Profiler http report: https://ufile.io/75yro3jl ),And your trace results seems not very enough for more results shall stat the state more comprehensively.

**Comment by ksiezak** [comment] 2023-03-29 09:02
@lurais I reuploaded profiler results:
https://home.nadajnik.org/profiler-results.html

As for trace should I run trace again but with more samples (longer duration)?

**Comment by lurais** [comment] 2023-03-29 10:23
> @lurais I reuploaded profiler results: https://home.nadajnik.org/profiler-results.html
> 
> As for trace should I run trace again but with more samples (longer duration)?

@ksiezak the profiler results is available now ,and run trace again in longer duration and in deeper method may be helpful. for example, org.tron.core.db.Manager:preValidateTransactionSign takes a lot percent , and you can just trace into the preValidateTransactionSign method to find the root cause of time occupation.

**Comment by ethan1844** [comment] 2023-04-12 03:12
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.

**Closed by ethan1844** 2023-04-12 03:12 UTC
Labels: topic:Net
