### ISSUE TITLE
 Process finished with non-zero exit value 134

### ISSUE THREAD

**Issue by bondibox** [tronprotocol/java-tron#494] opened 2018-04-20 14:45 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
java-tron commit efd604d7711cc4fc309795f8be27e4ddc24b8610
./gradlew run -Pwitness=true
9h 54m 20s

2. What did you expect to see?
Continued Operation

3. What did you see instead?

  A fatal error has been detected by the Java Runtime Environment:
  
   SIGBUS (0x7) at pc=0x00007ff9c99950fa, pid=2160, tid=0x00007ff97635d700
  
  JRE version: Java(TM) SE Runtime Environment (8.0_161-b12) (build 1.8.0_161-b12)
  Java VM: Java HotSpot(TM) 64-Bit Server VM (25.161-b12 mixed mode linux-amd64 compressed oops)
  Problematic frame:
  C  [libc.so.6+0x840fa]
  
  Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
  
  An error report file with more information is saved as:
  /root/java-tron/hs_err_pid2160.log
  
  If you would like to submit a bug report, please visit:
    http://bugreport.java.com/bugreport/crash.jsp
  The crash happened outside the Java Virtual Machine in native code.
  See problematic frame for where to report the bug.
  
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 134

ALSO
I expected hs_err_pid2160.log to be in java-tron/logs/ and not the root of the application.
hs_err_pid2160.log is a blank file 0 k

**Comment by bondibox** [comment] 2018-04-20 14:49
Is this an issue for Oracle?

**Comment by bondibox** [comment] 2018-04-20 14:55
This could have been just an old fashioned disk full error.

**Comment by huzhenyuan** [comment] 2018-05-08 09:52
Single machine problem. Could not reproduce. 
Suggest pull the latest version to test.
Temporarily close it. 
If appear again, then reopen it.

**Closed by huzhenyuan** 2018-05-08 09:52 UTC
Labels: bug
