### ISSUE TITLE
transaction broadcast success, but transaction not found in block

### ISSUE THREAD

**Issue by nbit99** [tronprotocol/java-tron#4312] opened 2022-03-02 05:01 UTC
tx hash:3d65cd021239bd39e3b41f4a9a150a50ee14ea4594c69d055d3640cfe56c239a

tron version: FullNode-v4.4.4.jar
The log:
```
12:30:43.897 INFO [qtp1047634424-255] net Fast send to /8.210.93.147:18888, type: INVENTORY
invType: TRX, size: 1, First hash: 3d65cd021239bd39e3b41f4a9a150a50ee14ea4594c69d055d3640cfe56c239a
12:30:43.898 INFO [qtp1047634424-255] net Fast send to /47.75.77.31:18888, type: INVENTORY
invType: TRX, size: 1, First hash: 3d65cd021239bd39e3b41f4a9a150a50ee14ea4594c69d055d3640cfe56c239a
12:30:43.898 INFO [qtp1047634424-255] net Fast send to /8.214.95.222:18888, type: INVENTORY
invType: TRX, size: 1, First hash: 3d65cd021239bd39e3b41f4a9a150a50ee14ea4594c69d055d3640cfe56c239a
12:30:43.898 INFO [qtp1047634424-255] net Fast send to /112.5.37.53:18888, type: INVENTORY
invType: TRX, size: 1, First hash: 3d65cd021239bd39e3b41f4a9a150a50ee14ea4594c69d055d3640cfe56c239a
12:30:43.898 INFO [qtp1047634424-255] net Fast send to /13.212.145.249:18888, type: INVENTORY
invType: TRX, size: 1, First hash: 3d65cd021239bd39e3b41f4a9a150a50ee14ea4594c69d055d3640cfe56c239a
12:30:43.898 INFO [qtp1047634424-255] net Fast send to /47.104.153.187:9888, type: INVENTORY
invType: TRX, size: 1, First hash: 3d65cd021239bd39e3b41f4a9a150a50ee14ea4594c69d055d3640cfe56c239a
12:30:43.898 INFO [qtp1047634424-255] net Fast send to /111.221.44.70:18888, type: INVENTORY
invType: TRX, size: 1, First hash: 3d65cd021239bd39e3b41f4a9a150a50ee14ea4594c69d055d3640cfe56c239a
12:30:43.898 INFO [qtp1047634424-255] net Fast send to /47.242.246.219:9888, type: INVENTORY
invType: TRX, size: 1, First hash: 3d65cd021239bd39e3b41f4a9a150a50ee14ea4594c69d055d3640cfe56c239a
12:30:43.898 INFO [qtp1047634424-255] o.t.c.Wallet Broadcast transaction 3d65cd021239bd39e3b41f4a9a150a50ee14ea4594c69d055d3640cfe56c239a to 8 peers successfully.
12:30:44.078 INFO [pool-52-thread-3] DB Tapos failed, different block hash, 14258, 47eb15d6cbc2d321 , recent block 3d7afe057261c506, solid block Num:38549408,ID:00000000024c37a07c7bec07d742659d213b25fd692770c92b830bd1d941725e head block Num:38549426,ID:00000000024c37b23d7afe057261c506e6b8aeba07fce4b2b8bfadb853d309e5
```

**Comment by nbit99** [comment] 2022-03-02 07:45
> @nbit99 After your transaction is executed, a tapos error occurs, the log is as follows.
> 
> 12:30:43.924 WARN [pool-52-thread-4] net Trx 3d65cd021239bd39e3b41f4a9a150a50ee14ea4594c69d055d3640cfe56c239a from peer /47.242.64.203 process failed. type: 12, trx exe failed, reason: org.tron.core.exception.TaposException: Tapos failed
> 
> In order to increase the success rate of broadcast transactions, you can set `trx.reference.block = "solid"`

My node has been set trx.reference.block = "solid" before this transaction，But the problem still occur frequently。

When I broadcast this transaction again，error：
[9001]BroadcastTransaction error message: Tapos check error.

**Comment by nbit99** [comment] 2022-03-02 08:08
When I set trx.reference.block = "solid"，The transaction broadcast is success, But The transaction will fail in no set trx.reference.block = "solid" node. So this problem happens！

**Comment by wubin01** [comment] 2022-03-02 09:58
Did you also create a transaction through this node?
The node that creates the transaction needs to be set `trx.reference.block = "solid"`

**Comment by nbit99** [comment] 2022-03-02 12:26
Yes,this is my main_net_config.conf
```
block = {
  needSyncCheck = true
  maintenanceTimeInterval = 21600000
  proposalExpireTime = 259200000 // 3 day: 259200000(ms)
}

# Transaction reference block, default is "head", configure to "solid" can avoid TaPos error
trx.reference.block = "solid" // head;solid;

# This property sets the number of milliseconds after the creation of the transaction that is expired, default value is  60000.
# trx.expiration.timeInMilliseconds = 60000

vm = {
  supportConstant = true
  minTimeRatio = 0.0
  maxTimeRatio = 20.0
  saveInternalTx = true

  # In rare cases, transactions that will be within the specified maximum execution time (default 10(ms)) are re-executed and packaged
  # longRunningTime = 10
}
```

**Comment by nbit99** [comment] 2022-03-02 12:29
My node success log:
o.t.c.Wallet Broadcast transaction 3d65cd021239bd39e3b41f4a9a150a50ee14ea4594c69d055d3640cfe56c239a to 8 peers successfully.

**Comment by wubin01** [comment] 2022-03-03 03:57
@nbit99  First confirm the following two questions, the intuition is caused by one of the problems.
1. does the config file take effect?
2. Which full-node do you use to create the transaction, is the same full-node used to create the transaction and broadcast the transaction?

**Comment by nbit99** [comment] 2022-03-04 08:50
It is same!

**Comment by wubin01** [comment] 2022-03-04 09:05
> It is same!

@nbit99 Another reason could be that your node is synchronizing blocks and the blocks are too far behind, more than 65536.

**Comment by wubin01** [comment] 2022-03-07 06:26
> It is same!

@nbit99 does the config file take effect?

**Comment by ethan1844** [comment] 2022-04-11 02:53
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.

**Closed by ethan1844** 2022-04-11 02:53 UTC
Labels: topic:Net
