### ISSUE TITLE
Why did TRON node synchronization stop?

### ISSUE THREAD

**Issue by zlxadata** [tronprotocol/java-tron#6123] opened 2024-12-16 08:33 UTC
The status of our TRON node is: the node program is running, but it has stopped syncing. The latest synchronized block number is 60344647, and it has remained at this block number without any updates.

We checked the tron.log file and found the following exception information:
Caused by: org.tron.core.exception.ContractValidateException: delegateBalance must be less than available FreezeEnergyV2 balance
Except for this type of exception, no other error messages were seen.

Is this the reason why the node stopped syncing?

If this is not the reason why the node stopped syncing, are there any other prompts in tron.log that are worth paying attention to?

Please help me, thank you very much!
![1](https://github.com/user-attachments/assets/957df00f-c081-4237-b5e8-ef9b5ddd8053)
![2](https://github.com/user-attachments/assets/23a98d98-d47c-4463-8f81-346343cab943)

**Comment by DongDongSunny** [comment] 2024-12-16 08:48
@zlxadata could please paste more info at the end of the log?

**Comment by CarlChaoCarl** [comment] 2024-12-16 08:51
@zlxadata Could you filter out the ERROR logs from tron.log? This will help find the issues more easily.

**Comment by zlxadata** [comment] 2024-12-17 01:35
> @zlxadata could please paste more info at the end of the log?

Hello!
Thank you for your reply. I took some extra screenshots from the log. Because the log contains too much content, I especially took some screenshots containing "ERROR" information. Could you please help me see if these contents are valuable?
![tron-log-1](https://github.com/user-attachments/assets/64fdc4ba-ee69-4093-b5e5-6a0d3178ebe1)
![tron-log-2](https://github.com/user-attachments/assets/e1ecbe25-5eb5-4bb8-9fb5-a601a6058e6c)
![tron-log-3](https://github.com/user-attachments/assets/e44adaf8-7726-4939-92fc-0dc40202be31)
![tron-log-4](https://github.com/user-attachments/assets/057bd62c-2f2e-478c-973f-55e6399cfa93)

**Comment by zlxadata** [comment] 2024-12-17 02:18
> @zlxadata Could you filter out the ERROR logs from tron.log? This will help find the issues more easily.

Most of the ERROR messages I saw were: Get contract failed, the account does not exist or the account does not have a code hash!,

But there are also two special ERROR messages:

1.Process block failed, Num:60344652,ID:000000000398c94cbd62d9f86081761f4badf83262e9e16e6b1f18e0d188c796, reason: delegateBalance must be less than available FreezeEnergyV2 balance

2.Process sync block Num:60344652,ID:000000000398c94cbd62d9f86081761f4badf83262e9e16e6b1f18e0d188c796 failed
The second prompt should be that the synchronization of block 60344652 failed, so the node synchronization stopped

I don’t know which of the above ERROR information is the real reason.

**Comment by DongDongSunny** [comment] 2024-12-17 02:31
@zlxadata could you please try to download the latest snapshot data from [here](http://34.143.247.77/) , then restart the service, it may caused by the wrong data status if there is some local changes with java-tron code

**Comment by zlxadata** [comment] 2024-12-17 07:32
> @zlxadata could you please try to download the latest snapshot data from [here](http://34.143.247.77/) , then restart the service, it may caused by the wrong data status if there is some local changes with java-tron code, then it stuck with sync the failed block. Or the data is corrupted somehow

Received, thank you very much for your suggestion!
I understand that there are some internal errors in the node file during operation, and this cannot be intervened by the outside. This is the second time I have encountered this situation, that is, syncing to a certain block, and then unable to continue syncing.
I feel that TRON's node synchronization is still imperfect.
It seems that the only way is to download and deploy a new node snapshot file.

**Comment by vivian1912** [comment] 2024-12-27 00:11
@zlxadata Thanks for your contribution to java-tron, this issue will be closed as no update for a long time. Please feel free to re-open it if you still see the issue, thanks.

**Closed by vivian1912** 2024-12-27 00:11 UTC
Labels: type:docs
