### ISSUE TITLE
Tronscan.org let login with any pwd

### ISSUE THREAD

**Issue by oroblu** [tronprotocol/java-tron#586] opened 2018-05-01 09:54 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
LogIN in tronscan.org with a random password string

2. What did you expect to see?
A message that deny login

3. What did you see instead?
It let me login

**Comment by Rovak** [comment] 2018-05-01 09:59
duplicate of #395

**Closed by Rovak** 2018-05-01 09:59 UTC
