### ISSUE TITLE
Website problems

### ISSUE THREAD

**Issue by Johnsavadkuhi** [tronprotocol/java-tron#340] opened 2018-03-31 10:21 UTC
a lot of problems in tron website but no one is responsible 

@zhaohong

**Comment by Rovak** [comment] 2018-03-31 13:51
Hi @Johnsavadkuhi, could specify which problems you are encountering?

A link to the specific page and a description of the problem would be helpful. If there are visual errors then please include a screenshot.

**Comment by BeatzCoin** [comment] 2018-04-01 00:33
The problem I have is that I signed up a while ago, and when I try to log in, it says email or password is wrong. Then when I click on "forgot password" I enter my email but clicking the "send authentication email" does nothing.

**Comment by Rovak** [comment] 2018-04-01 16:32
I just checked the "Forget Password" method myself and i received a mail from `noreply6@tronlab.com` within a few seconds. 

The website doesn't show any popup that the mail has been send, which is confusing

**Comment by zhaohong** [comment] 2018-04-02 03:05
@BeatzCoin   do you mean tron.network?

**Comment by a49688448** [comment] 2018-04-02 03:18
https://tron.network/ 
we will add popup to tell users that the mail has been send.

**Comment by Johnsavadkuhi** [comment] 2018-04-02 10:52
1  :    no website icon 
![tron_icon](https://user-images.githubusercontent.com/6722877/38192974-ddc3ff1e-3684-11e8-8048-68cfb8bd9a72.png)

2 :  profile page is accessible when user logouts  

![profile page](https://user-images.githubusercontent.com/6722877/38193285-8b40cebe-3686-11e8-95a2-17f02a9e2a4c.png)

3  : uncommon background of  inactivated and  activated label  :   

3 : 1 :  ![activated](https://user-images.githubusercontent.com/6722877/38193511-a8dfcd20-3687-11e8-8e3d-e98f4fb176cd.png)

3 : 2  : ![profile page](https://user-images.githubusercontent.com/6722877/38193285-8b40cebe-3686-11e8-95a2-17f02a9e2a4c.png)  

recommend for activated label background color  "#4441fd "  
recommend for inactivated label background color  "#fdb741"

4 :  a long time to get the validation link  

5 : forget password 

![pass](https://user-images.githubusercontent.com/6722877/38193832-619556fe-3689-11e8-9769-12dae82036ff.png)

**Comment by a49688448** [comment] 2018-04-02 11:06
Thank you for your feedback and have arranged for follow-up fix.

**Comment by a49688448** [comment] 2018-04-03 13:22
@Johnsavadkuhi we have fixed NO.1,2,5
NO.3. May not a bug.
NO.4. We suggest that 
     a. check that whether your network is ok. 
     b. you may find the email in junk mail box.

**Comment by tykkz** [comment] 2018-04-05 15:38
I registered on the website today and it took almost 5 minutes to get the email to my YANDEX mail address.

I guess the main reason behind this delay is that you guys are using Alibaba cloud for SMTP delivery.

**Comment by Rovak** [comment] 2018-04-09 21:00
I just checked and 1, 2, 5 have been fixed. 3 and 4 are not really bugs but could be improved later. Closing for now.

**Closed by Rovak** 2018-04-09 21:00 UTC
Labels: website
