### ISSUE TITLE
OUT_OF_ENERGY when deploying contract on privatenet

### ISSUE THREAD

**Issue by kevholder** [tronprotocol/java-tron#3300] opened 2020-07-21 18:01 UTC
I'm getting `OUT_OF_ENERGY` error when deploy a contract on privatenet.

```bash
$ npx tronbox migrate
Using network 'development'.

Running migration: 2_deploy_contract.js
  Deploying GravatarRegistry...
ERROR: Contract GravatarRegistry has not been deployed on the network.
For more details, check the transaction at:
http://127.0.0.1:18190/wallet/gettransactionbyid?value=c2557ae4f2621700b620f76fa8ec776d2fc8c91d8ebb64598483d41c3eff0bd4
If the transaction above is empty, most likely, your address had no bandwidth/energy to deploy the contract.
```

http://127.0.0.1:18190/wallet/gettransactionbyid?value=c2557ae4f2621700b620f76fa8ec776d2fc8c91d8ebb64598483d41c3eff0bd4

```json
{
  "ret": [
    {
      "contractRet": "OUT_OF_ENERGY"
    }
  ],
  "signature": [
    "5ead00b621701239336faa6bebb7a6ef2345974527b48857cfef17bdbfd62ea17a4435b04be03d8fd4c593dc9107d31267807bf291ecc5713d22d5f3c315514e00"
  ],
  "txID": "c2557ae4f2621700b620f76fa8ec776d2fc8c91d8ebb64598483d41c3eff0bd4",
  "contract_address": "41827579d1dd0ef554f48bbca8996727f3ea0125af",
  "raw_data": {
    "contract": [
      {
        "parameter": {
          "value": {
            "owner_address": "41928c9af0651632157ef27a2cf17ca72c575a4d21",
            "new_contract": {
              "bytecode": "608060405234801561001057600080fd5b50d3801561001d57600080fd5b50d2801561002a57600080fd5b506115d78061003a6000396000f30060806040526004361061008d576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806281d6e5146100925780631d4f2c6d14610115578063359c1f721461014657806388d0d39114610288578063a5ac36341461030f578063b18588fb14610380578063cdb3344a14610403578063d5ce24ed146104cc575b600080fd5b34801561009e57600080fd5b50d380156100ab57600080fd5b50d280156100b857600080fd5b50610113600480360381019080803590602001908201803590602001908080601f016020809104026020016040519081016040528093929190818152602001838380828437820191505050505050919291929050505061062b565b005b34801561012157600080fd5b50d3801561012e57600080fd5b50d2801561013b57600080fd5b50610144610930565b005b34801561015257600080fd5b50d3801561015f57600080fd5b50d2801561016c57600080fd5b506101a1600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050610ace565b604051808060200180602001838103835285818151815260200191508051906020019080838360005b838110156101e55780820151818401526020810190506101ca565b50505050905090810190601f1680156102125780820380516001836020036101000a031916815260200191505b50838103825284818151815260200191508051906020019080838360005b8381101561024b578082015181840152602081019050610230565b50505050905090810190601f1680156102785780820380516001836020036101000a031916815260200191505b5094505050505060405180910390f35b34801561029457600080fd5b50d380156102a157600080fd5b50d280156102ae57600080fd5b506102cd60048036038101908080359060200190929190505050610c97565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34801561031b57600080fd5b50d3801561032857600080fd5b50d2801561033557600080fd5b5061036a600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050610cca565b6040518082815260200191505060405180910390f35b34801561038c57600080fd5b50d3801561039957600080fd5b50d280156103a657600080fd5b50610401600480360381019080803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509192919290505050610ce2565b005b34801561040f57600080fd5b50d3801561041c57600080fd5b50d2801561042957600080fd5b506104ca600480360381019080803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509192919290803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509192919290505050610fe7565b005b3480156104d857600080fd5b50d380156104e557600080fd5b50d280156104f257600080fd5b50610511600480360381019080803590602001909291905050506112fd565b604051808473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020018060200180602001838103835285818151815260200191508051906020019080838360005b8381101561058757808201518184015260208101905061056c565b50505050905090810190601f1680156105b45780820380516001836020036101000a031916815260200191505b50838103825284818151815260200191508051906020019080838360005b838110156105ed5780820151818401526020810190506105d2565b50505050905090810190601f16801561061a5780820380516001836020036101000a031916815260200191505b509550505050505060405180910390f35b600080600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020541415151561067b57600080fd5b6000600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020548154811015156106c957fe5b906000526020600020906003020160000160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614151561073457600080fd5b600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205490508160008281548110151561078657fe5b906000526020600020906003020160020190805190602001906107aa929190611486565b507f76571b7a897a1509c641587568218a290018fbdc8b9a724f17b77ff0eec22c0c81336000848154811015156107dd57fe5b906000526020600020906003020160010185604051808581526020018473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200180602001806020018381038352858181546001816001161561010002031660029004815260200191508054600181600116156101000203166002900480156108b45780601f10610889576101008083540402835291602001916108b4565b820191906000526020600020905b81548152906001019060200180831161089757829003601f168201915b5050838103825284818151815260200191508051906020019080838360005b838110156108ee5780820151818401526020810190506108d3565b50505050905090810190601f16801561091b5780820380516001836020036101000a031916815260200191505b50965050505050505060405180910390a15050565b738d3e809fbd258083a5ba004a527159da535c8aba73ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614151561097e57600080fd5b6000606060405190810160405280600073ffffffffffffffffffffffffffffffffffffffff1681526020016040805190810160405280600181526020017f200000000000000000000000000000000000000000000000000000000000000081525081526020016040805190810160405280600181526020017f20000000000000000000000000000000000000000000000000000000000000008152508152509080600181540180825580915050906001820390600052602060002090600302016000909192909190915060008201518160000160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055506020820151816001019080519060200190610aab929190611506565b506040820151816002019080519060200190610ac8929190611506565b50505050565b6060806000600260008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020549050600081815481101515610b2457fe5b9060005260206000209060030201600101600082815481101515610b4457fe5b9060005260206000209060030201600201818054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015610bea5780601f10610bbf57610100808354040283529160200191610bea565b820191906000526020600020905b815481529060010190602001808311610bcd57829003601f168201915b50505050509150808054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015610c865780601f10610c5b57610100808354040283529160200191610c86565b820191906000526020600020905b815481529060010190602001808311610c6957829003601f168201915b505050505090509250925050915091565b60016020528060005260406000206000915054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60026020528060005260406000206000915090505481565b600080600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205414151515610d3257600080fd5b6000600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054815481101515610d8057fe5b906000526020600020906003020160000160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141515610deb57600080fd5b600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054905081600082815481101515610e3d57fe5b90600052602060002090600302016001019080519060200190610e61929190611486565b507f76571b7a897a1509c641587568218a290018fbdc8b9a724f17b77ff0eec22c0c813384600085815481101515610e9557fe5b9060005260206000209060030201600201604051808581526020018473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020018060200180602001838103835285818151815260200191508051906020019080838360005b83811015610f22578082015181840152602081019050610f07565b50505050905090810190601f168015610f4f5780820380516001836020036101000a031916815260200191505b50838103825284818154600181600116156101000203166002900481526020019150805460018160011615610100020316600290048015610fd15780601f10610fa657610100808354040283529160200191610fd1565b820191906000526020600020905b815481529060010190602001808311610fb457829003601f168201915b5050965050505050505060405180910390a15050565b600080600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205414151561103657600080fd5b600160006060604051908101604052803373ffffffffffffffffffffffffffffffffffffffff168152602001868152602001858152509080600181540180825580915050906001820390600052602060002090600302016000909192909190915060008201518160000160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555060208201518160010190805190602001906110fa929190611506565b506040820151816002019080519060200190611117929190611506565b505050039050336001600083815260200190815260200160002060006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555080600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055507f9ab3aefb2ba6dc12910ac1bce4692cf5c3c0d06cff16327c64a3ef78228b130b81338585604051808581526020018473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020018060200180602001838103835285818151815260200191508051906020019080838360005b83811015611254578082015181840152602081019050611239565b50505050905090810190601f1680156112815780820380516001836020036101000a031916815260200191505b50838103825284818151815260200191508051906020019080838360005b838110156112ba57808201518184015260208101905061129f565b50505050905090810190601f1680156112e75780820380516001836020036101000a031916815260200191505b50965050505050505060405180910390a1505050565b60008181548110151561130c57fe5b90600052602060002090600302016000915090508060000160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1690806001018054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156113de5780601f106113b3576101008083540402835291602001916113de565b820191906000526020600020905b8154815290600101906020018083116113c157829003601f168201915b505050505090806002018054600181600116156101000203166002900480601f01602080910402602001604051908101604052809291908181526020018280546001816001161561010002031660029004801561147c5780601f106114515761010080835404028352916020019161147c565b820191906000526020600020905b81548152906001019060200180831161145f57829003601f168201915b5050505050905083565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106114c757805160ff19168380011785556114f5565b828001600101855582156114f5579182015b828111156114f45782518255916020019190600101906114d9565b5b5090506115029190611586565b5090565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061154757805160ff1916838001178555611575565b82800160010185558215611575579182015b82811115611574578251825591602001919060010190611559565b5b5090506115829190611586565b5090565b6115a891905b808211156115a457600081600090555060010161158c565b5090565b905600a165627a7a7230582054585f58068ffd42c757934361ac6f53cc99a3be42bbd04210d18305233587520029",
              "name": "GravatarRegistry",
              "origin_address": "41928c9af0651632157ef27a2cf17ca72c575a4d21",
              "abi": {
                "entrys": [
                  {
                    "outputs": [
                      {
                        "type": "address"
                      }
                    ],
                    "constant": true,
                    "inputs": [
                      {
                        "type": "uint256"
                      }
                    ],
                    "name": "gravatarToOwner",
                    "stateMutability": "View",
                    "type": "Function"
                  },
                  {
                    "outputs": [
                      {
                        "type": "uint256"
                      }
                    ],
                    "constant": true,
                    "inputs": [
                      {
                        "type": "address"
                      }
                    ],
                    "name": "ownerToGravatar",
                    "stateMutability": "View",
                    "type": "Function"
                  },
                  {
                    "outputs": [
                      {
                        "name": "owner",
                        "type": "address"
                      },
                      {
                        "name": "displayName",
                        "type": "string"
                      },
                      {
                        "name": "imageUrl",
                        "type": "string"
                      }
                    ],
                    "constant": true,
                    "inputs": [
                      {
                        "type": "uint256"
                      }
                    ],
                    "name": "gravatars",
                    "stateMutability": "View",
                    "type": "Function"
                  },
                  {
                    "inputs": [
                      {
                        "name": "id",
                        "type": "uint256"
                      },
                      {
                        "name": "owner",
                        "type": "address"
                      },
                      {
                        "name": "displayName",
                        "type": "string"
                      },
                      {
                        "name": "imageUrl",
                        "type": "string"
                      }
                    ],
                    "name": "NewGravatar",
                    "type": "Event"
                  },
                  {
                    "inputs": [
                      {
                        "name": "id",
                        "type": "uint256"
                      },
                      {
                        "name": "owner",
                        "type": "address"
                      },
                      {
                        "name": "displayName",
                        "type": "string"
                      },
                      {
                        "name": "imageUrl",
                        "type": "string"
                      }
                    ],
                    "name": "UpdatedGravatar",
                    "type": "Event"
                  },
                  {
                    "inputs": [
                      {
                        "name": "_displayName",
                        "type": "string"
                      },
                      {
                        "name": "_imageUrl",
                        "type": "string"
                      }
                    ],
                    "name": "createGravatar",
                    "stateMutability": "Nonpayable",
                    "type": "Function"
                  },
                  {
                    "outputs": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "string"
                      }
                    ],
                    "constant": true,
                    "inputs": [
                      {
                        "name": "owner",
                        "type": "address"
                      }
                    ],
                    "name": "getGravatar",
                    "stateMutability": "View",
                    "type": "Function"
                  },
                  {
                    "inputs": [
                      {
                        "name": "_displayName",
                        "type": "string"
                      }
                    ],
                    "name": "updateGravatarName",
                    "stateMutability": "Nonpayable",
                    "type": "Function"
                  },
                  {
                    "inputs": [
                      {
                        "name": "_imageUrl",
                        "type": "string"
                      }
                    ],
                    "name": "updateGravatarImage",
                    "stateMutability": "Nonpayable",
                    "type": "Function"
                  },
                  {
                    "name": "setMythicalGravatar",
                    "stateMutability": "Nonpayable",
                    "type": "Function"
                  }
                ]
              },
              "origin_energy_limit": 10000000
            }
          },
          "type_url": "type.googleapis.com/protocol.CreateSmartContract"
        },
        "type": "CreateSmartContract"
      }
    ],
    "ref_block_bytes": "1e47",
    "ref_block_hash": "f9f56d3f712572b9",
    "expiration": 1595354118000,
    "fee_limit": 100000000,
    "timestamp": 1595354060579
  },
  "raw_data_hex": "0a021e472208f9f56d3f712572b940f0ee8f94b72e5a8b32081e1286320a30747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e437265617465536d617274436f6e747261637412d1310a1541928c9af0651632157ef27a2cf17ca72c575a4d2112b7310a1541928c9af0651632157ef27a2cf17ca72c575a4d211af2040a2d10011a0f6772617661746172546f4f776e657222091a0775696e743235362a091a0761646472657373300240020a2d10011a0f6f776e6572546f477261766174617222091a07616464726573732a091a0775696e74323536300240020a5910011a0967726176617461727322091a0775696e743235362a1012056f776e65721a07616464726573732a15120b646973706c61794e616d651a06737472696e672a121208696d61676555726c1a06737472696e67300240020a5b1a0b4e65774772617661746172220d120269641a0775696e74323536221012056f776e65721a07616464726573732215120b646973706c61794e616d651a06737472696e6722121208696d61676555726c1a06737472696e6730030a5f1a0f557064617465644772617661746172220d120269641a0775696e74323536221012056f776e65721a07616464726573732215120b646973706c61794e616d651a06737472696e6722121208696d61676555726c1a06737472696e6730030a411a0e63726561746547726176617461722216120c5f646973706c61794e616d651a06737472696e67221312095f696d61676555726c1a06737472696e67300240030a3910011a0b6765744772617661746172221012056f776e65721a07616464726573732a081a06737472696e672a081a06737472696e67300240020a301a1275706461746547726176617461724e616d652216120c5f646973706c61794e616d651a06737472696e67300240030a2e1a137570646174654772617661746172496d616765221312095f696d61676555726c1a06737472696e67300240030a191a137365744d7974686963616c47726176617461723002400322912c608060405234801561001057600080fd5b50d3801561001d57600080fd5b50d2801561002a57600080fd5b506115d78061003a6000396000f30060806040526004361061008d576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806281d6e5146100925780631d4f2c6d14610115578063359c1f721461014657806388d0d39114610288578063a5ac36341461030f578063b18588fb14610380578063cdb3344a14610403578063d5ce24ed146104cc575b600080fd5b34801561009e57600080fd5b50d380156100ab57600080fd5b50d280156100b857600080fd5b50610113600480360381019080803590602001908201803590602001908080601f016020809104026020016040519081016040528093929190818152602001838380828437820191505050505050919291929050505061062b565b005b34801561012157600080fd5b50d3801561012e57600080fd5b50d2801561013b57600080fd5b50610144610930565b005b34801561015257600080fd5b50d3801561015f57600080fd5b50d2801561016c57600080fd5b506101a1600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050610ace565b604051808060200180602001838103835285818151815260200191508051906020019080838360005b838110156101e55780820151818401526020810190506101ca565b50505050905090810190601f1680156102125780820380516001836020036101000a031916815260200191505b50838103825284818151815260200191508051906020019080838360005b8381101561024b578082015181840152602081019050610230565b50505050905090810190601f1680156102785780820380516001836020036101000a031916815260200191505b5094505050505060405180910390f35b34801561029457600080fd5b50d380156102a157600080fd5b50d280156102ae57600080fd5b506102cd60048036038101908080359060200190929190505050610c97565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34801561031b57600080fd5b50d3801561032857600080fd5b50d2801561033557600080fd5b5061036a600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050610cca565b6040518082815260200191505060405180910390f35b34801561038c57600080fd5b50d3801561039957600080fd5b50d280156103a657600080fd5b50610401600480360381019080803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509192919290505050610ce2565b005b34801561040f57600080fd5b50d3801561041c57600080fd5b50d2801561042957600080fd5b506104ca600480360381019080803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509192919290803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509192919290505050610fe7565b005b3480156104d857600080fd5b50d380156104e557600080fd5b50d280156104f257600080fd5b50610511600480360381019080803590602001909291905050506112fd565b604051808473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020018060200180602001838103835285818151815260200191508051906020019080838360005b8381101561058757808201518184015260208101905061056c565b50505050905090810190601f1680156105b45780820380516001836020036101000a031916815260200191505b50838103825284818151815260200191508051906020019080838360005b838110156105ed5780820151818401526020810190506105d2565b50505050905090810190601f16801561061a5780820380516001836020036101000a031916815260200191505b509550505050505060405180910390f35b600080600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020541415151561067b57600080fd5b6000600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020548154811015156106c957fe5b906000526020600020906003020160000160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614151561073457600080fd5b600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205490508160008281548110151561078657fe5b906000526020600020906003020160020190805190602001906107aa929190611486565b507f76571b7a897a1509c641587568218a290018fbdc8b9a724f17b77ff0eec22c0c81336000848154811015156107dd57fe5b906000526020600020906003020160010185604051808581526020018473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200180602001806020018381038352858181546001816001161561010002031660029004815260200191508054600181600116156101000203166002900480156108b45780601f10610889576101008083540402835291602001916108b4565b820191906000526020600020905b81548152906001019060200180831161089757829003601f168201915b5050838103825284818151815260200191508051906020019080838360005b838110156108ee5780820151818401526020810190506108d3565b50505050905090810190601f16801561091b5780820380516001836020036101000a031916815260200191505b50965050505050505060405180910390a15050565b738d3e809fbd258083a5ba004a527159da535c8aba73ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614151561097e57600080fd5b6000606060405190810160405280600073ffffffffffffffffffffffffffffffffffffffff1681526020016040805190810160405280600181526020017f200000000000000000000000000000000000000000000000000000000000000081525081526020016040805190810160405280600181526020017f20000000000000000000000000000000000000000000000000000000000000008152508152509080600181540180825580915050906001820390600052602060002090600302016000909192909190915060008201518160000160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055506020820151816001019080519060200190610aab929190611506565b506040820151816002019080519060200190610ac8929190611506565b50505050565b6060806000600260008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020549050600081815481101515610b2457fe5b9060005260206000209060030201600101600082815481101515610b4457fe5b9060005260206000209060030201600201818054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015610bea5780601f10610bbf57610100808354040283529160200191610bea565b820191906000526020600020905b815481529060010190602001808311610bcd57829003601f168201915b50505050509150808054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015610c865780601f10610c5b57610100808354040283529160200191610c86565b820191906000526020600020905b815481529060010190602001808311610c6957829003601f168201915b505050505090509250925050915091565b60016020528060005260406000206000915054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60026020528060005260406000206000915090505481565b600080600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205414151515610d3257600080fd5b6000600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054815481101515610d8057fe5b906000526020600020906003020160000160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141515610deb57600080fd5b600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002054905081600082815481101515610e3d57fe5b90600052602060002090600302016001019080519060200190610e61929190611486565b507f76571b7a897a1509c641587568218a290018fbdc8b9a724f17b77ff0eec22c0c813384600085815481101515610e9557fe5b9060005260206000209060030201600201604051808581526020018473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020018060200180602001838103835285818151815260200191508051906020019080838360005b83811015610f22578082015181840152602081019050610f07565b50505050905090810190601f168015610f4f5780820380516001836020036101000a031916815260200191505b50838103825284818154600181600116156101000203166002900481526020019150805460018160011615610100020316600290048015610fd15780601f10610fa657610100808354040283529160200191610fd1565b820191906000526020600020905b815481529060010190602001808311610fb457829003601f168201915b5050965050505050505060405180910390a15050565b600080600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205414151561103657600080fd5b600160006060604051908101604052803373ffffffffffffffffffffffffffffffffffffffff168152602001868152602001858152509080600181540180825580915050906001820390600052602060002090600302016000909192909190915060008201518160000160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555060208201518160010190805190602001906110fa929190611506565b506040820151816002019080519060200190611117929190611506565b505050039050336001600083815260200190815260200160002060006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555080600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055507f9ab3aefb2ba6dc12910ac1bce4692cf5c3c0d06cff16327c64a3ef78228b130b81338585604051808581526020018473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020018060200180602001838103835285818151815260200191508051906020019080838360005b83811015611254578082015181840152602081019050611239565b50505050905090810190601f1680156112815780820380516001836020036101000a031916815260200191505b50838103825284818151815260200191508051906020019080838360005b838110156112ba57808201518184015260208101905061129f565b50505050905090810190601f1680156112e75780820380516001836020036101000a031916815260200191505b50965050505050505060405180910390a1505050565b60008181548110151561130c57fe5b90600052602060002090600302016000915090508060000160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1690806001018054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156113de5780601f106113b3576101008083540402835291602001916113de565b820191906000526020600020905b8154815290600101906020018083116113c157829003601f168201915b505050505090806002018054600181600116156101000203166002900480601f01602080910402602001604051908101604052809291908181526020018280546001816001161561010002031660029004801561147c5780601f106114515761010080835404028352916020019161147c565b820191906000526020600020905b81548152906001019060200180831161145f57829003601f168201915b5050505050905083565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106114c757805160ff19168380011785556114f5565b828001600101855582156114f5579182015b828111156114f45782518255916020019190600101906114d9565b5b5090506115029190611586565b5090565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061154757805160ff1916838001178555611575565b82800160010185558215611575579182015b82811115611574578251825591602001919060010190611559565b5b5090506115829190611586565b5090565b6115a891905b808211156115a457600081600090555060010161158c565b5090565b905600a165627a7a7230582054585f58068ffd42c757934361ac6f53cc99a3be42bbd04210d183052335875200293a10477261766174617252656769737472794080ade20470a3ae8c94b72e900180c2d72f"
}
```

This error does not happen with smaller contracts. The private key I am using has a lot of privatenet TRX so I don't understand how to fix the issue.

**Comment by Starsakary** [comment] 2020-07-23 08:49
I guess this may be caused by your setting of 'originEnergyLimit'. This field limits the maximum resource consumption.

**Comment by Starsakary** [comment] 2020-07-29 07:24
Without args details, I suggest setting the fee limit at 1,000,000,000, which can probably solve your problem.

**Comment by Benson0224** [comment] 2020-08-27 06:58
> Without args details, I suggest setting the fee limit at 1,000,000,000, which can probably solve your problem.

since Sakary already gives the answer, I will close this issue, please reopen it and provide us more info if you still see the issue, thanks.

**Closed by Benson0224** 2020-08-27 06:58 UTC
Labels: topic: Smart contract
