### ISSUE TITLE
JAVA crash on startup on GreatVoyage-v4.7.1.1 and  v4.7.1 and v4.7.0.1 on Linux

### ISSUE THREAD

**Issue by devfxplayer** [tronprotocol/java-tron#5187] opened 2023-04-28 14:35 UTC
14:28:23,529 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [API] to INFO
14:28:23,529 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [witness] to INFO
14:28:23,529 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [DB] to INFO
14:28:23,529 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [capsule] to INFO
14:28:23,529 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [VM] to INFO
14:28:23,529 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [LEVELDB] to INFO
14:28:23,529 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [LEVELDB] to false
14:28:23,529 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [DB] to Logger[LEVELDB]
14:28:23,529 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [ROCKSDB] to INFO
14:28:23,529 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [ROCKSDB] to false
14:28:23,529 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [DB] to Logger[ROCKSDB]
14:28:23,529 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [tool] to INFO
14:28:23,529 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [tool] to false
14:28:23,529 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[tool]
14:28:23,529 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
14:28:23,529 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@16c0663d - Registering current configuration as safe fallback point

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0x00007f8b4f30b3da, pid=13484, tid=0x00007f8b4fe9a700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_321-b07) (build 1.8.0_321-b07)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.321-b07 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0xbb3da]
#
# Core dump written. Default location: /usr/java/jre1.8.0_321/bin/core or core.13484
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid13484.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted

**Comment by m-o-m12** [comment] 2023-04-29 14:10
Full log helps to find out the root cause.

**Comment by devfxplayer** [comment] 2023-05-02 08:55
hello, thanks we found out that the disk space was full.

**Comment by ethan1844** [comment] 2023-05-25 07:02
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.

**Closed by ethan1844** 2023-05-25 07:02 UTC
Labels: topic: Deployment

**Comment by dhruvja** [comment] 2023-06-23 15:46
> hello, thanks we found out that the disk space was full.

How much disk space is needed?

**Comment by guoquanwu** [comment] 2023-06-24 16:50
> > hello, thanks we found out that the disk space was full.
> 
> How much disk space is needed?

2T+ is recommended, for more info refer here: https://github.com/tronprotocol/java-tron

**Comment by dhruvja** [comment] 2023-06-25 08:17
> 

to even start up the node?

**Comment by dhruvja** [comment] 2023-06-25 08:17
> > 
> 
> to even start up the node?

**Comment by dhruvja** [comment] 2023-06-25 08:17
> > > hello, thanks we found out that the disk space was full.
> > 
> > 
> > How much disk space is needed?
> 
> 2T+ is recommended, for more info refer here: https://github.com/tronprotocol/java-tron

To even start up the node?

**Comment by guoquanwu** [comment] 2023-06-25 08:26
> > > > hello, thanks we found out that the disk space was full.
> > > 
> > > 
> > > How much disk space is needed?
> > 
> > 
> > 2T+ is recommended, for more info refer here: https://github.com/tronprotocol/java-tron
> 
> To even start up the node? I just wanted to run on a localnet and not sync with mainnet.

This depends on the amount of data in your local node, there is no limit.

**Comment by dhruvja** [comment] 2023-06-25 12:56
> > > > > hello, thanks we found out that the disk space was full.
> > > > 
> > > > 
> > > > How much disk space is needed?
> > > 
> > > 
> > > 2T+ is recommended, for more info refer here: https://github.com/tronprotocol/java-tron
> > 
> > 
> > To even start up the node? I just wanted to run on a localnet and not sync with mainnet.
> 
> This depends on the amount of data in your local node, there is no limit.

Does starting a private network mean a local node? I can only see the config for mainnet, testnet and private network.

**Comment by lurais** [comment] 2023-06-25 14:33
> 

@dhruvja Starting a private network mean a local node with the private network config file used, you can refer to this link to find more detail: https://developers.tron.network/docs/tron-private-chain
