### ISSUE TITLE
Contract can be created with null bytecode

### ISSUE THREAD

**Issue by tlatkdgus1** [tronprotocol/java-tron#2848] opened 2020-01-09 07:17 UTC
### 1. What did you do?
When I deployed test contract, fill empty bytecode in payload, I can expected success response

and can i attach in tronide
![image](https://user-images.githubusercontent.com/13446909/72047344-ac79ce80-32fd-11ea-9c18-e178162bf3f2.png)

here is my test contract 
[https://shasta.tronscan.org/#/contract/TCmeKAnkHjm6y9xDxLmE1u3YLXbLfo5R1E/code](url)

### 2. What did you expect to see?
meaning error

### 3. What did you see instead?
response from **/wallet/deploycontract**

`{ 
"visible":false,
"txID":"968be1b28778253a82198e658663e49c872564e4e14b79cadac8eb1997a99f28",
"contract_address":"416e9efeffc3aa63c36ca9b70a8144e8be8477afda",
"raw_data":{ 
"contract":[ 
{ 
"parameter":{ 
"value":{ 
"owner_address":"41babf033a8794cb3e46127d1ca76e669fa2d28887",
"new_contract":{ 
"origin_address":"41babf033a8794cb3e46127d1ca76e669fa2d28887",
"abi":{ 
"entrys":[ 
{ 
"outputs":[ 
{ 
"type":"uint256"
}
],
"constant":true,
"name":"blogMain_getValue",
"stateMutability":"View",
"type":"Function"
},
{ 
"inputs":[ 
{ 
"name":"_value",
"type":"uint256"
}
],
"name":"blogMain_setValue",
"stateMutability":"Nonpayable",
"type":"Function"
}
]
},
"origin_energy_limit":10000000
}
},
"type_url":"type.googleapis.com/protocol.CreateSmartContract"
},
"type":"CreateSmartContract"
}
],
"ref_block_bytes":"0cd1",
"ref_block_hash":"5d7062e8d88de899",
"expiration":1578553863000,
"fee_limit":300000000,
"timestamp":1578553805674
},
"raw_data_hex":"0a020cd122085d7062e8d88de89940d8d691c9f82d5ac301081e12be010a30747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e437265617465536d617274436f6e74726163741289010a1541babf033a8794cb3e46127d1ca76e669fa2d2888712700a1541babf033a8794cb3e46127d1ca76e669fa2d288871a520a2410011a11626c6f674d61696e5f67657456616c75652a091a0775696e74323536300240020a2a1a11626c6f674d61696e5f73657456616c7565221112065f76616c75651a0775696e74323536300240034080ade20470ea968ec9f82d900180c6868f01"
}`

**Comment by guoquanwu** [comment] 2020-01-09 14:23
try again? still no err? I tried contract with null bytecode, but didn't reproduce your problem

**Comment by tlatkdgus1** [comment] 2020-01-10 08:14
here is my request json
and endpoint is 

https://api.shasta.trongrid.io/wallet/deploycontract/

![image](https://user-images.githubusercontent.com/13446909/72136371-00eb7f80-33cc-11ea-95b7-b373d917be78.png)

reponse
![image](https://user-images.githubusercontent.com/13446909/72136479-3a23ef80-33cc-11ea-913d-0e7e7754b25d.png)


so I find contract on tronscan ( contract : 415de6a1623407e8ebb4d9a3ce15f5ff7870a85034 -> TJXi8P2r6RssvaNgDuVW15XsZohmAVHsna )

[wrong contract in tron scan](https://shasta.tronscan.org/#/contract/TJXi8P2r6RssvaNgDuVW15XsZohmAVHsna/code)

**Comment by andelf** [comment] 2020-01-13 09:01
This is unexpected behavior. Labeled as Bug.
(At least on Shasta testnet & Nile testnet.)

**Comment by andelf** [comment] 2020-01-13 10:04
Update:

On Mainnet:

```
txID: fcf0c791a05d163aff8fe330190e25573e06955689431b162b770f1ce2f87832
Contract Address: TCTXgXij9GqVSs6P74eXfEfhNgvmhHgpao
```

**Comment by tlatkdgus1** [comment] 2020-01-14 10:24
anyone can test another field possible to null or empty ?

**Comment by Sh11thead** [comment] 2020-01-16 08:23
Hello,The root cause of the problem is that TVM itself can accept and execute empty bytecodes and return a normal execution result. Whether this feature continues to be retained requires further evaluation. If the creation of empty bytecode contracts is prohibited, changes need to be made in TVM. 
This need Hard fork in a future release

**Comment by jiangyy0824** [comment] 2020-02-03 05:41
Hello,

If your problem has been solved, please close this issue.

Thank you!

**Comment by tlatkdgus1** [comment] 2020-02-03 08:20
> Hello,
> 
> If your problem has been solved, please close this issue.
> 
> Thank you!

Hello jiangyy,
I think this issue is not solved, if you think this issue is not important. you can close this.

Thank you :)

**Comment by andelf** [comment] 2020-02-06 15:03
FYI: EVM allows contracts with empty code too.
<https://etherscan.io/address/0xd8253352f6044cfe55bcc0748c3fa37b7df81f98#code>

**Comment by Benson0224** [comment] 2020-08-27 06:39
> FYI: EVM allows contracts with empty code too.
> https://etherscan.io/address/0xd8253352f6044cfe55bcc0748c3fa37b7df81f98#code

As Andelf mentioned, EVM also allows contracts with empty code, and it is a hard fork change, should be handled via TIP process. Please check [TIP](https://github.com/tronprotocol/tips) process and submit a TIP if this is really a must for you, thanks.

**Closed** 2020-08-27 06:40 UTC
Labels: topic: Smart contract, type: Bug, type: Question
