### ISSUE TITLE
[Web] Possible to create account without using Register tab

### ISSUE THREAD

**Issue by shymi80** [tronprotocol/java-tron#668] opened 2018-05-08 12:00 UTC
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
- Open https://tronscan.org/
- Click "Register / Log-in"
- Stay on "Login" tab
- input any at least 40 chars long string to "Private Key" field
- click "Login"

2. What did you expect to see?
Login error as there was no account with such private key previously created by usage of "Register" tab and checking proper checkboxes.

3. What did you see instead?
- Account was created and I am able to login
![image](https://user-images.githubusercontent.com/38183098/39755973-07bf6312-52c8-11e8-985e-2c8ccd497d58.png)

**Comment by Rovak** [comment] 2018-05-08 12:02
Duplicate of https://github.com/tronprotocol/wallet-web/issues/20

**Closed by Rovak** 2018-05-08 12:02 UTC
