### ISSUE TITLE
How to add notes when creating a transaction

### ISSUE THREAD

**Issue by ha1i1uya** [tronprotocol/java-tron#2954] opened 2020-02-20 11:06 UTC
### 2. What did you expect to see?
When I  transfer trx 、trc10 or trc20 to others by api, the transaction can be with notes

### 3. What did you see instead?
Notes can be used only for locally constructed transactions. There is no such field in the api

**Comment by andelf** [comment] 2020-02-21 03:30
Transfering TRX with a note: <https://shasta.tronscan.org/#/transaction/be48f2889edec428584b86c5a087133e7c27b2cd801379dedaff209af95945c4>

Transfering TRC10 with a note:
<https://api.shasta.tronscan.org/api/transaction-info?hash=3c70c0f0f20f4c02e90409b8b6f582319889288ffa8b30688993ab003e345992>
> yet, tronscan can not display note info for TRC10 transfer transactions.

For TRC20, The type of the transfer function is:

    function transfer(address _to, uint256 _value) returns (bool)

So, it naturally does not support a field called `note` or `memo`. 


For detail:

> You can use the ``Transaction.raw.data`` field as the note for any type of transaction. (gRPC API works)

**Comment by ha1i1uya** [comment] 2020-02-21 03:53
yes it is memo. and It can be used only for constructed transaction ,javatron native api still can not do it,what i want is that api also support a memo for all kinds of transactions

**Comment by andelf** [comment] 2020-02-21 08:31
OK, I will close this issue for that it's a duplicate of #2953 .
And that's a feature request. You can follow the development progress.

**Closed by andelf** 2020-02-21 08:31 UTC
Labels: resolution: Duplicated, topic: Block/Transaction, type: Question

**Comment by clearcodecn** [comment] 2023-12-14 09:18
@andelf  How to use  `Transaction.raw.data` as notes ? change it after transaction build , before sign ?
