### ISSUE TITLE
How to calculate energy consumption of sending TRC20 Token?

### ISSUE THREAD

**Issue by lujunZhang** [tronprotocol/java-tron#2982] opened 2020-02-28 03:27 UTC
Hi Tron,

I'm a developer from Bitpie Wallet. When sending USDT (TRC20), if there is not enough energy or TRON, this transaction will fail. I didn't find a way to estimate the energy that will be consumed by a transaction before sending it. 

For users to have a better experience using TRON, we want to show users the bandwidth, energy and TRON needed before sending the transaction. So that users won't send transactions that will fail. 

Can you provide a method to calculate energy consumption?

**Comment by jingniao** [comment] 2020-02-28 06:47
same question !!!
Looking forward to the solution

**Comment by guoquanwu** [comment] 2020-02-28 06:48
You can check this doc: https://developers.tron.network/docs/resource-model

If these docs do not help you, please let me know.

**Comment by guoquanwu** [comment] 2020-02-28 06:48
> Hi Tron,
> 
> I'm a developer from Bitpie Wallet. When sending USDT (TRC20), if there is not enough energy or TRON, this transaction will fail. I didn't find a way to estimate the energy that will be consumed by a transaction before sending it.
> 
> For users to have a better experience using TRON, we want to show users the bandwidth, energy and TRON needed before sending the transaction. So that users won't send transactions that will fail.
> 
> Can you provide a method to calculate energy consumption?

You can check this doc: https://developers.tron.network/docs/resource-model

If these docs do not help you, please let me know.

**Comment by lujunZhang** [comment] 2020-02-28 13:06
> > Hi Tron,
> > I'm a developer from Bitpie Wallet. When sending USDT (TRC20), if there is not enough energy or TRON, this transaction will fail. I didn't find a way to estimate the energy that will be consumed by a transaction before sending it.
> > For users to have a better experience using TRON, we want to show users the bandwidth, energy and TRON needed before sending the transaction. So that users won't send transactions that will fail.
> > Can you provide a method to calculate energy consumption?
> 
> You can check this doc: https://developers.tron.network/docs/resource-model
> 
> If these docs do not help you, please let me know.

This doc didn't solve my problem, I still don't know how to calculate the energy consumption by a transaction before sending it.

**Comment by guoquanwu** [comment] 2020-02-28 13:36
> > > Hi Tron,
> > > I'm a developer from Bitpie Wallet. When sending USDT (TRC20), if there is not enough energy or TRON, this transaction will fail. I didn't find a way to estimate the energy that will be consumed by a transaction before sending it.
> > > For users to have a better experience using TRON, we want to show users the bandwidth, energy and TRON needed before sending the transaction. So that users won't send transactions that will fail.
> > > Can you provide a method to calculate energy consumption?
> > 
> > 
> > You can check this doc: https://developers.tron.network/docs/resource-model
> > If these docs do not help you, please let me know.
> 
> This doc didn't solve my problem, I still don't know how to calculate the energy consumption by a transaction before sending it.

I think we can get how to calculate Bandwidth for a transaction and how to get user's bandwidth and energy from the doc above, 
Actually, you can consider that USDT20 is a smart contract on java-tron,  the calculation method is the same as that of other smart contracts. 
So in my opinion, the energy of transfer USDT is at a fixed cost, you can have a test to see whether it is right.
The above is for reference only.

I am also consulting the members of the community, I believe they will show a correct answer later, please be patient.

**Comment by guoquanwu** [comment] 2020-03-01 10:53
I have confirmed with the community members, energy is usually a fixed cost, and you can get from TronScan or though the getcontract api. 

Hope this can help you.

**Comment by jingniao** [comment] 2020-03-02 01:54
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_estimategas

**Comment by guoquanwu** [comment] 2020-03-02 03:27
> eth has api eth_estimategas to do this......
> https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_estimategas

As java-tron's energy model is not the same as ETH's gas model,  but it does be a useful functions, we can suggest the community develop this function.

Maybe you can propose a new TIP to talk about this. here is how to propose a TIP.
https://github.com/tronprotocol/tips

**Comment by jiangyy0824** [comment] 2020-03-23 04:34
If your problem is solved, please close this issue, thanks.

**Closed** 2020-03-25 01:13 UTC
Labels: topic: Resource manage

**Comment by kevholder** [comment] 2020-06-14 23:59
@lujunZhang how did you solve the problem? I haven't figured out yet how to get energy estimate from API.

**Comment by BigMurry** [comment] 2020-07-21 07:30
I found a strange situation, for TRC20 USDT token transfer method, it costs 29631 energy sometimes, but it costs 14631 energy other times.
see these two txs below which were mined in the same block, the first one costed 29631 but the second one costed 14631
https://tronscan.io/#/transaction/611ffb9f35cee7dc2b32493325e8813684f1c218c9a5f52dcf9ca10957686975
https://tronscan.io/#/transaction/f07410b34c47cf629f608ed7d4cb793fd22b2a746dc2cececdbba08a21af6842

**Comment by shixiaofeia** [comment] 2020-12-09 07:12
> 我发现一个奇怪的情况下,对于TRC20 USDT令牌传输方法,有时候29631年能源成本,但成本14631年能源其他时间。
> 见下面的这两个tx开采在同一块,29631年第一个估价,但第二个花费14631
> [https://tronscan.io/ /交易/ 611 ffb9f35cee7dc2b32493325e8813684f1c218c9a5f52dcf9ca10957686975 ](https://tronscan.io/#/transaction/611ffb9f35cee7dc2b32493325e8813684f1c218c9a5f52dcf9ca10957686975)
> [https://tronscan.io/ /交易/ f07410b34c47cf629f608ed7d4cb793fd22b2a746dc2cececdbba08a21af6842 ](https://tronscan.io/#/transaction/f07410b34c47cf629f608ed7d4cb793fd22b2a746dc2cececdbba08a21af6842)


I also encountered this problem, do you know the reason?

**Comment by guoquanwu** [comment] 2020-12-09 10:13
> > 我发现一个奇怪的情况下,对于TRC20 USDT令牌传输方法,有时候29631年能源成本,但成本14631年能源其他时间。
> > 见下面的这两个tx开采在同一块,29631年第一个估价,但第二个花费14631
> > [https://tronscan.io/ /交易/ 611 ffb9f35cee7dc2b32493325e8813684f1c218c9a5f52dcf9ca10957686975 ](https://tronscan.io/#/transaction/611ffb9f35cee7dc2b32493325e8813684f1c218c9a5f52dcf9ca10957686975)
> > [https://tronscan.io/ /交易/ f07410b34c47cf629f608ed7d4cb793fd22b2a746dc2cececdbba08a21af6842 ](https://tronscan.io/#/transaction/f07410b34c47cf629f608ed7d4cb793fd22b2a746dc2cececdbba08a21af6842)
> 
> I also encountered this problem, do you know the reason?

Energy cost is calculated by the number and the type of OP command compiled from the contract, if all `transfer()` in the USDT contract executes the same codes, the energy cost will be the same. 
So I guess maybe the USDT TRC20 contract has some special logic, like someone goes to `if()` and others will go to `else`?  You can check the USDT contract to confirm.

**Comment by shixiaofeia** [comment] 2020-12-09 10:32
> > > 我发现一个奇怪的情况下,对于TRC20 USDT令牌传输方法,有时候29631年能源成本,但成本14631年能源其他时间。
> > > 见下面的这两个tx开采在同一块,29631年第一个估价,但第二个花费14631
> > > [https://tronscan.io/ /交易/ 611 ffb9f35cee7dc2b32493325e8813684f1c218c9a5f52dcf9ca10957686975 ](https://tronscan.io/#/transaction/611ffb9f35cee7dc2b32493325e8813684f1c218c9a5f52dcf9ca10957686975)
> > > [https://tronscan.io/ /交易/ f07410b34c47cf629f608ed7d4cb793fd22b2a746dc2cececdbba08a21af6842 ](https://tronscan.io/#/transaction/f07410b34c47cf629f608ed7d4cb793fd22b2a746dc2cececdbba08a21af6842)
> > 
> > 
> > I also encountered this problem, do you know the reason?
> 
> Energy cost is calculated by the number and the type of OP command compiled from the contract, if all `transfer()` in the USDT contract executes the same codes, the energy cost will be the same.
> So I guess maybe the USDT TRC20 contract has some special logic, like someone goes to `if()` and others will go to `else`? You can check the USDT contract to confirm.

Thanks for the reply, I mentioned this in another https://github.com/tronprotocol/java-tron/issues/3556

**Comment by novaxdeveloper** [comment] 2021-04-10 23:13
i have same question 
no answer?

**Comment by Benson0224** [comment] 2021-04-14 09:24
> i have same question
> no answer?
Check this guide:
https://developers.tron.network/docs/faq#5-how-to-calculate-the-bandwidth-and-energy-consumed-when-calling-the-contract

**Comment by prih** [comment] 2021-05-12 14:43
?

**Comment by samanshahmohamadi** [comment] 2021-06-08 09:47
I also encountered this issue. As I understand, in case of calling transfer method of a trc20 contract, there are two possible values for energy consumption: 
1. if the receiver address did not receive a transaction on the specific trc20 contract (say USDT-TRC20), energy consumption would be exactly 29631.  
2. if the receiver address already received a transaction on the specific trc20 contract, energy consumption would be exactly 14631.  

But we need a method for estimating the energy consumption before sending the transaction, just like `estimateGas` method in eth libraries.

**Comment by Benson0224** [comment] 2021-06-08 10:05
Thanks for your sharing.
The root cause is the cost of OP code `SSTORE` is different between "reset", "add" and "delete." it is the same for all TRC20 tokens. 

![image](https://user-images.githubusercontent.com/61768920/121166309-8b673580-c883-11eb-84af-ffbbc4336349.png)

check more detail at:  https://developers.tron.network/docs/energy-cost 

Currently, Tron doesn't support `estimateGas` method.  The best practice of querying the energy cost is to check the history transactions. thanks.

**Comment by MohsenHaydari** [comment] 2022-08-09 18:12
> Thanks for your sharing. The root cause is the cost of OP code `SSTORE` is different between "reset", "add" and "delete." it is the same for all TRC20 tokens.
> 
> ![image](https://user-images.githubusercontent.com/61768920/121166309-8b673580-c883-11eb-84af-ffbbc4336349.png)
> 
> check more detail at: https://developers.tron.network/docs/energy-cost
> 
> Currently, Tron doesn't support `estimateGas` method. The best practice of querying the energy cost is to check the history transactions. thanks.

Tron supports this method and it works correctly, the only problem is that if the method  called does not work correctly and the revert is executed, it displays the amount of energy consumed on the same place, and if the method is executed correctly, the amount of energy It is true,I use this [post ](https://stackoverflow.com/a/73222761/10149535)to calculate the amount of energy consumption, and the amount is correct

**Comment by joeytwiddle** [comment] 2022-08-11 20:53
It looks to me like the costs slightly increased recently:

- For empty recipient: **29650 energy** (previously 29631)

  https://tronscan.org/#/transaction/7698f9a64f4e47e2f5b79bcf5402501dd5f39df69e127f19e62998aa7cc76bdb

  That totals to **8.647 TRX** (previously 8.64168), or **8.302 TRX** when using free/staked bandwidth

- For non-empty recipient: **14650 energy** (previously 14631)

  https://tronscan.org/#/transaction/7b21b125bc7f870edd1140df70884ebfa92d1a734baa92f0937ff04e49de27bb

  That totals to **4.447 TRX** (previously 4.44168) or **4.102 TRX** when using free/staked bandwidth

Can anyone confirm if these are the correct energy costs now? Could they go higher?

And could anyone explain _why_ these numbers increased? Thanks!

@samanshahmohamadi How did you get your numbers? I only found them by browsing through TronScan.

**Comment by vincentes** [comment] 2022-09-23 18:55
Is there no info about this? No total energy formula?

**Comment by prih** [comment] 2022-09-23 18:59
> Is there no info about this? No total energy formula?

this is no longer relevant, just use **/wallet/triggerconstantcontract** call the desired method and you will find the **energy_used** value, such a call will work for any smart contract method

**Comment by vincentes** [comment] 2022-09-24 17:01
> > Is there no info about this? No total energy formula?
> 
> this is no longer relevant, just use **/wallet/triggerconstantcontract** call the desired method and you will find the **energy_used** value, such a call will work for any smart contract method

Tthat endpoint gives me this error.
```javascript

  stack: 'SyntaxError: OpenAPI schema validation failed.\n' +
    '\n' +
    "REQUIRED must have required property 'responses'\n" +
```

**Comment by inmortalbobz** [comment] 2022-09-24 17:33
> Hi Tron,
> 
> I'm a developer from Bitpie Wallet. When sending USDT (TRC20), if there is not enough energy or TRON, this transaction will fail. I didn't find a way to estimate the energy that will be consumed by a transaction before sending it. 
> 
> For users to have a better experience using TRON, we want to show users the bandwidth, energy and TRON needed before sending the transaction. So that users won't send transactions that will fail. 
> 
> Can you provide a method to calculate energy consumption?
> 

It depends on how long you are wanting to wait, the faster the more expensive the transaction will be

**Comment by abdulgig** [comment] 2022-10-12 12:13
> > Is there no info about this? No total energy formula?
> 
> this is no longer relevant, just use **/wallet/triggerconstantcontract** call the desired method and you will find the **energy_used** value, such a call will work for any smart contract method

Can you share a working example ? I tried using it and I am getting the error,

`curl -X POST -d '{
"contract_address": "412dd04f7b26176aa130823bcc67449d1f451eb98f",
"owner_address": "411fafb1e96dfe4f609e2259bfaf8c77b60c535b93",
"function_selector": "transfer (address, uint256)",
"parameter": "0000000000000000000000002ed5dd8a98aea00ae32517742ea5289761b2710e0000000000000000000000000000000000000000000000000000000ba43b7400",
"call_value": 0,
"fee_limit": 1000000000,
"call_token_value": 0,
"token_id": 0
} ' https://api.trongrid.io/wallet/triggerconstantcontract
{"result":{"code":"CONTRACT_VALIDATE_ERROR","message":"536d61727420636f6e7472616374206973206e6f742065786973742e"}}
`

**Comment by Akash4686** [comment] 2022-10-13 11:14
> > > Is there no info about this? No total energy formula?
> > 
> > 
> > this is no longer relevant, just use **/wallet/triggerconstantcontract** call the desired method and you will find the **energy_used** value, such a call will work for any smart contract method
> 
> Can you share a working example ? I tried using it and I am getting the error,
> 
> `curl -X POST -d '{ "contract_address": "412dd04f7b26176aa130823bcc67449d1f451eb98f", "owner_address": "411fafb1e96dfe4f609e2259bfaf8c77b60c535b93", "function_selector": "transfer (address, uint256)", "parameter": "0000000000000000000000002ed5dd8a98aea00ae32517742ea5289761b2710e0000000000000000000000000000000000000000000000000000000ba43b7400", "call_value": 0, "fee_limit": 1000000000, "call_token_value": 0, "token_id": 0 } ' https://api.trongrid.io/wallet/triggerconstantcontract {"result":{"code":"CONTRACT_VALIDATE_ERROR","message":"536d61727420636f6e7472616374206973206e6f742065786973742e"}}`

We are also getting same response

by using visible true this error says "Smart contract is not found".

even on documentation it says same.
https://developers.tron.network/reference/triggerconstantcontract

if we go into further docs where they are showing us how to encode parameters they have an example which is working
https://developers.tron.network/docs/parameter-and-return-value-encoding-and-decoding

but in smart_contract_address, a non active account address is being sent in that example.

I tried with USDT smart contract nothing is working.
Totally confused right now.

**Comment by maxcotech** [comment] 2023-01-15 13:58
> It looks to me like the costs slightly increased recently:
> 
> * For empty recipient: **29650 energy** (previously 29631)
>   https://tronscan.org/#/transaction/7698f9a64f4e47e2f5b79bcf5402501dd5f39df69e127f19e62998aa7cc76bdb
>   That totals to **8.647 TRX** (previously 8.64168), or **8.302 TRX** when using free/staked bandwidth
> * For non-empty recipient: **14650 energy** (previously 14631)
>   https://tronscan.org/#/transaction/7b21b125bc7f870edd1140df70884ebfa92d1a734baa92f0937ff04e49de27bb
>   That totals to **4.447 TRX** (previously 4.44168) or **4.102 TRX** when using free/staked bandwidth
> 
> **Update:** These TRX values are now out-of-date, since the energy price changed from 280 sun to 420 sun on 2022/12/04
> 
> Can anyone confirm if these are the correct energy costs now? Could they go higher?
> 
> And could anyone explain _why_ these numbers increased? Thanks!
> 
> @samanshahmohamadi How did you get your numbers? I only found them by browsing through TronScan.

please which endpoint did you used to get 420 sun?

**Comment by MohsenHaydari** [comment] 2023-01-15 16:37
shasta

> > It looks to me like the costs slightly increased recently:
> > 
> > * For empty recipient: **29650 energy** (previously 29631)
> >   https://tronscan.org/#/transaction/7698f9a64f4e47e2f5b79bcf5402501dd5f39df69e127f19e62998aa7cc76bdb
> >   That totals to **8.647 TRX** (previously 8.64168), or **8.302 TRX** when using free/staked bandwidth
> > * For non-empty recipient: **14650 energy** (previously 14631)
> >   https://tronscan.org/#/transaction/7b21b125bc7f870edd1140df70884ebfa92d1a734baa92f0937ff04e49de27bb
> >   That totals to **4.447 TRX** (previously 4.44168) or **4.102 TRX** when using free/staked bandwidth
> > 
> > **Update:** These TRX values are now out-of-date, since the energy price changed from 280 sun to 420 sun on 2022/12/04
> > Can anyone confirm if these are the correct energy costs now? Could they go higher?
> > And could anyone explain _why_ these numbers increased? Thanks!
> > @samanshahmohamadi How did you get your numbers? I only found them by browsing through TronScan.
> 
> please which endpoint did you used to get 420 sun?
https://api.trongrid.io/wallet/getchainparameters

**Comment by maxcotech** [comment] 2023-01-15 20:04
> shasta
> 
> > > It looks to me like the costs slightly increased recently:
> > > 
> > > * For empty recipient: **29650 energy** (previously 29631)
> > >   https://tronscan.org/#/transaction/7698f9a64f4e47e2f5b79bcf5402501dd5f39df69e127f19e62998aa7cc76bdb
> > >   That totals to **8.647 TRX** (previously 8.64168), or **8.302 TRX** when using free/staked bandwidth
> > > * For non-empty recipient: **14650 energy** (previously 14631)
> > >   https://tronscan.org/#/transaction/7b21b125bc7f870edd1140df70884ebfa92d1a734baa92f0937ff04e49de27bb
> > >   That totals to **4.447 TRX** (previously 4.44168) or **4.102 TRX** when using free/staked bandwidth
> > > 
> > > **Update:** These TRX values are now out-of-date, since the energy price changed from 280 sun to 420 sun on 2022/12/04
> > > Can anyone confirm if these are the correct energy costs now? Could they go higher?
> > > And could anyone explain _why_ these numbers increased? Thanks!
> > > @samanshahmohamadi How did you get your numbers? I only found them by browsing through TronScan.
> > 
> > 
> > please which endpoint did you used to get 420 sun?
> > https://api.trongrid.io/wallet/getchainparameters
> 
> ```
>   {
>             "key": "getEnergyFee",
>             "value": 420
>         },
> ```

Awesome thanks alot , please do you mind if I ask how you can use this to energy fee to determine transaction cost in sun

**Comment by caglarvolkan** [comment] 2023-02-14 18:51
It is finally here: https://developers.tron.network/docs/set-feelimit#how-to-estimate-energy-consumption

**Comment by sc0Vu** [comment] 2023-07-26 03:34
There is dynamic energy model in Tron. Basically, each smart contract transaction would cost base fee and additional fee (base fee won't change). The additional fee comes from another energy_factor, can fetch by wallet/getcontractinfo api. The more energy the contract consumes, the higher energy_factor would be. (now it cost 31895 to transfer usdt)

https://developers.tron.network/docs/resource-model#dynamic-energy-model

**Comment by parisahrad** [comment] 2023-08-22 06:41
for anyone looking for the answer: 

```
    const CONTRACT = 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t';

    const contract = await tronWeb.contract().at(CONTRACT);

    const usdtAfterDecimalPlace = cryptoAmount * 1000000;

    const parameter1 = [
      { type: 'address', value: withdraw.destinationWalletAddress },
      { type: 'uint256', value: usdtAfterDecimalPlace },
    ];

    const transaction =
      await tronWeb.transactionBuilder.triggerConstantContract(
        CONTRACT,
        'transfer(address,uint256)',
        {},
        parameter1,
        fromAddress,
      );

    const energyToSun = transaction.energy_used * 420;
```

this is energy usage for transfering usdt on trc20

**Comment by widynek** [comment] 2023-10-04 16:35
Hello, using hints above I managed to get energy used from endpoint https://api.trongrid.io/wallet/triggerconstantcontract but I'm getting very low value- as low as 1657 for transferring USDT (expecting to get ~ 32 000).
Request params:

{"owner_address":"TFS43fT3Y7fpmTjEgVkciATLU8sBrzpN9s","visible":"true","contract_address":"TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t","function_selector":"transfer (address, uint256)","parameter":"a9059cbb0000000000000000000000003af6ac6cdd4894e43950fc58d2cc2a3a76afd753000000000000000000000000000000000000000000000000000000002775518"}
based on transaction found here: https://tronscan.org/#/transaction/489949cbe0eb8216578c9de552948f4fe4a9ce79952fff5a4a0e24bd9bb4db5a

Any thoughts what's wrong with my calls ?

**Comment by widynek** [comment] 2023-10-04 16:36
any thoughs appreciated [parisahrad](https://github.com/parisahrad)

**Comment by widynek** [comment] 2023-10-04 18:36
solved https://github.com/trustwallet/wallet-core/discussions/2786#discussioncomment-7189541

**Comment by Mae6e** [comment] 2023-12-15 10:19
@parisahrad 
this is feelimit. is it true?
feelimit = estimated energy consumption * energy unit price = energy_used * 420

reference: https://medium.com/tronnetwork/dynamic-energy-model-deployed-and-opened-on-nile-testnet-59b81cb748f5

**Comment by Sintayew4** [comment] 2024-04-22 18:42
#2982
