### ISSUE TITLE
unreasonable BANDWITH_ERROR

### ISSUE THREAD

**Issue by DmytroShalaiev** [tronprotocol/java-tron#3932] opened 2021-07-19 17:37 UTC
### 1. What did you do?
I have **635**/5,**673** (TMzhFJm4HFwjWaXxMt1u1n3MYXTbfySXeY) BP's on my wallet(right now) and try to send trc20 USDT
wich should consume ~345 BPS (such as previous tx's using sendRawTransaction tronWeb)

send
### 2. What did you expect to see?

Success transfer 

### 3. What did you see instead?
{ code: 'BANDWITH_ERROR',
txid:
'19a87387bcd9c1ee96705d5c3f30f455f18e45d1543d34bedc436ac07ed7827c',
message:
'4163636f756e745265736f75726365496e73756666696369656e74206572726f72' }

So, why error if I had 635 BP's and ALL-same previous tx's consume 345 BP's?

After some time ... I had **690**/5,**673**, and all complete well, and consume 345 BP's, why?
So, if I had frozen trx for BP's and BP's balance lower than BP's I got from frozen(673) + 17 BP's, I can not use them?!

**Comment by DmytroShalaiev** [comment] 2021-07-19 17:46
@sean-liu55 @Yrp @zhangheng1536

**Comment by Alexliu007** [comment] 2021-07-20 02:24
hi，There is not enough bandwidth or TRX to burn to send a transaction. Deposit TRX in the account, or use another account to delegate bandwidth to this account. 
![image](https://user-images.githubusercontent.com/33770261/126252621-4dbe2bc1-55f4-4507-be3f-d8db44faaf42.png)

**Comment by DmytroShalaiev** [comment] 2021-07-20 07:32
But, I had enough Bp's - 635 BPs... so after some time(later) all become good, maybe it's lag of node that I used for broadcast tx

**Comment by Alexliu007** [comment] 2021-07-20 08:17
> But, I had enough Bp's - 635 BPs... so after some time(later) all become good, maybe it's lag of node that I used for broadcast tx?

You can query the relevant resources of the address through the getaccountresource interface before transfer. pls refert to this document~https://developers.tron.network/reference#getaccountresource

**Comment by DmytroShalaiev** [comment] 2021-07-20 08:40
I did so, query resources, and log them, before broadcast tx

**Comment by Alexliu007** [comment] 2021-07-20 08:44
Do you use local nodes for broadcast transactions? You can check whether the next node is synchronized to the latest. This error is reported because of insufficient bandwidth and insufficient TRX burning in the address to obtain bandwidth.

**Comment by DmytroShalaiev** [comment] 2021-07-20 09:43
I used official tron Public nodes, so, the problem can be due to the node sync process?!

**Comment by Alexliu007** [comment] 2021-07-20 10:06
> I used official tron Public nodes, so, the problem can be due to the node sync process?! Before broadcasting tx I got account resources (from the same node) and got enough(600+ BP's) for tx, after broadcast... got an error instead.
> After some time, I had 412 BP's and broadcast tx using the same code - it completes.

Is it convenient to provide the node information? like IP infos, thanks!

**Comment by DmytroShalaiev** [comment] 2021-07-20 10:18
52.53.189.99:8090 || 3.225.171.164:8090 || 18.196.99.16:8090 (now got ECONNREFUSED)

Some of these 3 (I use dynamic node selection), sorry did not save exact logs from which node perform broadcasting

**Comment by DmytroShalaiev** [comment] 2021-07-20 13:23
Right now I reproduce same thing on tronWeb:http://35.180.51.163:8090

**Comment by DmytroShalaiev** [comment] 2021-07-20 15:17
**I got logs from this case**:
```

send RawTransaction executor starts...
tronWeb.fullNode.host:http://54.252.224.209:8090

**data for sendRawTransaction:**
{ txID:
'2693a018ab8eb269447367bd183c2c7236afcf55ecd06cb5b3970f191184e4e2',
raw_data:
{ contract: [ [Object] ],ef_block_bytes: 'e58f',
ref_block_hash: 'b066fdcb730d31d2',
expiration: 1626875697000,
fee_limit: 10000000,
timestamp: 1626792839284 },
raw_data_hex:
'0a02e58f2208b066fdcb730d31d240e8aee4caac2f5aae01081f12a9010a31747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e54726967676572536d617274436f6e747261637412740a154183e980ef65b11e372eadd115c1d5566df39bebdf121541a614f803b6fd780986a42c78ec9c7f77e6ded13c2244a9059cbb000000000000000000000000aa1066c40f00b9dee08875b811c2e73d167c4782000000000000000000000000000000000000000000000000000000000000000170f490a3a3ac2f900180ade204',
visible: false,
signature:
[ 'b5d4a0c23ee1e301560bcf9fc298007109905bd997b2fe43f75592809b1af14a7de4700af62fd7715007bc077cda42ddec3cd7c8057dee71921058a966a26ee100' ] 
}


**Account resources:**
{ 
freeNetUsed: 4762,
freeNetLimit: 5000,
NetUsed: 3607,
NetLimit: 3817,
assetNetUsed:
[ { key: '1004281', value: 0 },
{ key: '1004057', value: 0 },
{ key: '1002000', value: 0 },
{ key: '1004077', value: 0 },
{ key: '1004160', value: 0 },
{ key: '1003533', value: 0 } ],
assetNetLimit:
[ { key: '1003533', value: 0 },
{ key: '1004057', value: 0 },
{ key: '1002000', value: 0 },
{ key: '1004077', value: 0 },
{ key: '1004281', value: 0 },
{ key: '1004160', value: 0 } ],
TotalNetLimit: 43200000000,
TotalNetWeight: 30217137270,
EnergyUsed: 359017,
EnergyLimit: 419470,
TotalEnergyLimit: 90000000000,
TotalEnergyWeight: 3179725690 }

send trc20 tx, receipt:
{ code: 'BANDWITH_ERROR',
txid:
'2693a018ab8eb269447367bd183c2c7236afcf55ecd06cb5b3970f191184e4e2',
message:
'4163636f756e745265736f75726365496e73756666696369656e74206572726f72' }
```

1) What is assetNetUsed && assetNetLimit?
2) I saw such thing, Tx should consume 345 BP's, but in my case:

freeNetUsed: 4762,
freeNetLimit: 5000,
5000 - 4762 = 238 BP's from free quota 

NetUsed: 3607,
NetLimit: 3817,
3817 - 3607 =  210 BP's from frozen trx


So, 238 + 210 = 448  BP's for usage, why BANDWITH_ERROR?
I have only one explanation that free BP's cannot be combined with BP's from freeze for usage in one Tx.
So, tx in TRON cannot consume BP's from free + freeze balances... 
I'm not sure about anything anymore, how much I develop on TRON, more and more I come across inexplicable things about which have not been written anywhere.

**Comment by Alexliu007** [comment] 2021-07-21 02:28
The ordinary transaction, Bandwidth points consumption sequence:
1.Bandwidth points from freezing TRX. If transaction initiator does not have enough Bandwidth Points of this type, it will go to step 2;

2.Free Bandwidth points. If transaction initiator does not have enough Bandwidth Points of this type, it will go to step 3;

3.Bandwidth points from burning TRX, the rate = the number of bytes of the transaction * 140 SUN;

**Comment by DmytroShalaiev** [comment] 2021-07-21 07:28
@Alexliu007, Ok, then it turns out that I described everything correctly in my last comment, and you confirmed the guesses (we cannot mix different types of resources), thank you very much

**Comment by DmytroShalaiev** [comment] 2021-07-21 07:40
for TRC20 coin(USDT) I should use these rules, or rules in your last comment?

Token transfer transaction, Bandwidth points consumption sequence:

Firstly, check if the total free Bandwidth Points of the token issuer is enough. Then, check if the transfer Initiator‘s remaining token free bandwidth Points is enough. Finally check if the Bandwidth Points of token issuer obtained by freezing TRX is enough. Otherwise, it will go to step 2;
2.Bandwidth points from freezing TRX. If transaction initiator does not have enough Bandwidth Points of this type, it will go to step 3;
3.Free Bandwidth points. If transaction initiator does not have enough Bandwidth Points of this type, it will go to step 4;
4.Bandwidth points from burning TRX, the rate = the number of bytes of the transaction * 140 SUN;

**Comment by DmytroShalaiev** [comment] 2021-07-21 07:48
And, why I should check token issuer resources?

**Comment by Alexliu007** [comment] 2021-07-22 02:48
> for TRC20 coin(USDT) I should use these rules, or rules in your last comment?
> 
> Token transfer transaction, Bandwidth points consumption sequence:
> 
> Firstly, check if the total free Bandwidth Points of the token issuer is enough. Then, check if the transfer Initiator‘s remaining token free bandwidth Points is enough. Finally check if the Bandwidth Points of token issuer obtained by freezing TRX is enough. Otherwise, it will go to step 2;
> 2.Bandwidth points from freezing TRX. If transaction initiator does not have enough Bandwidth Points of this type, it will go to step 3;
> 3.Free Bandwidth points. If transaction initiator does not have enough Bandwidth Points of this type, it will go to step 4;
> 4.Bandwidth points from burning TRX, the rate = the number of bytes of the transaction * 140 SUN;

yes,it's same, If the contract sets the user fee percentage to account for 100%, it consumes the energy of the contract deployer. If the energy obtained by the contract deployer’s freezing is insufficient, the user’s energy or trx will still be deducted, pls refer to this document https://developers.tron.network/reference#walletdeploycontract-1

**Comment by DmytroShalaiev** [comment] 2021-07-22 08:04
Thank's for reply, and what about 
assetNetUsed:
[ { key: '1004281', value: 0 },
{ key: '1004057', value: 0 },
{ key: '1002000', value: 0 },
{ key: '1004077', value: 0 },
{ key: '1004160', value: 0 },
{ key: '1003533', value: 0 } ],
assetNetLimit:
[ { key: '1003533', value: 0 },
{ key: '1004057', value: 0 },
{ key: '1002000', value: 0 },
{ key: '1004077', value: 0 },
{ key: '1004281', value: 0 },
{ key: '1004160', value: 0 } ],

What is these in account resources model?

**Comment by Alexliu007** [comment] 2021-07-22 08:55
> assetNetUsed

assetNetUsed: The account has used the issuer bandwidth of the asset
assetNetLimit: The bandwidth limit of the asset owned by the account

**Comment by DmytroShalaiev** [comment] 2021-07-22 12:12
Ok, thanks, very thanks, I think we can close this issue

**Comment by Alexliu007** [comment] 2021-07-23 06:16
> Ok, thanks, very thanks, I think we can close this issue

sure, thanks!

**Comment by Benson0224** [comment] 2021-07-27 09:53
Thanks for your contribution to java-tron. 
This issue will be closed as the issue is already clarified, thanks.

**Closed by Benson0224** 2021-07-27 09:53 UTC
