### ISSUE TITLE
TRC20 token info is empty

### ISSUE THREAD

**Issue by Jutom17** [tronprotocol/java-tron#3741] opened 2021-04-13 09:03 UTC
### 1. What did you do?
I issued a TRC20 token (ILTU). I want to retrieve the token info when querying the TRC20 transactions by account address.

### 2. What did you expect to see?
The TRC20 transactions info by account address, and the token info as well

### 3. What did you see instead?

{
      "transaction_id": "9e65fa49fb3c35c2a0bbd3964eda41afcef5891cf17fd8f4c32711d8a2c43489",
      **"token_info": {},**
      "block_timestamp": 1618301214000,
      "from": "TGHsSSxAvvTR1WpFLP18XkJQnqSqh9wkb5",
      "to": "TTAWELC9oU76gfM8Zm6Em2C37uzMtQyYYi",
      "type": "Transfer",
      "value": "2000000"
    },

https://api.shasta.trongrid.io/v1/accounts/TTAWELC9oU76gfM8Zm6Em2C37uzMtQyYYi/transactions/trc20

**Comment by Benson0224** [comment] 2021-04-13 09:49
did you complete the token record step? if not please try below steps: 
https://shasta.tronscan.org/#/tokens/create/Type

**Comment by Jutom17** [comment] 2021-04-13 10:07
> 
> 
> did you complete the token record step? if not please try below steps:
> https://shasta.tronscan.org/#/tokens/create/Type

I have completed the recording step. Therefore, I can look up the token in shasta.

**Comment by Benson0224** [comment] 2021-04-14 03:53
Please check again, the issue is fixed now.

**Comment by Jutom17** [comment] 2021-04-14 05:26
fixed, thank @Benson0224

**Closed** 2021-04-14 05:32 UTC
