### ISSUE TITLE
为mainnet运行超级代表节点报错

### ISSUE THREAD

**Issue by caojianmin** [tronprotocol/java-tron#2412] opened 2019-08-13 06:42 UTC
C:\Users\Administrator\Desktop\test\fullnode>java -jar FullNode.jar -p 82f38d1f886912450321605e86b52fb938580da0750afe02fbd778b167fa2e79 --witness -c C:\Users\Administrator\Desktop\test\fullnode\config.conf
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$2 (file:/C:/Users/Administrator/Desktop/test/fullnode/FullNode.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
******** begin to pop revokingDb ********
******** before revokingDb size:0
******** end to pop revokingDb ********

**Comment by jiangyy0824** [comment] 2019-08-14 03:49
@caojianmin We suggest you deploy fullnode on linux environment, and we suggest you deploy witness node on your private network other than main-net. 

 The log is incomplete, we only see warnings. Please provide complete tron.log.

**Comment by caojianmin** [comment] 2019-08-14 03:54
@jiangyy0824 tron.log中的内容如下：
11:49:49.115 INFO  [main] [app](FullNode.java:44) Full node running.
11:49:49.744 INFO  [main] [app](Args.java:1198) Bind address wasn't set, Punching to identify it...
11:49:49.833 INFO  [main] [app](Args.java:1201) UDP local bound to: 172.168.1.119
11:49:49.838 INFO  [main] [app](Args.java:1216) External IP wasn't set, using checkip.amazonaws.com to identify it...
11:49:50.354 INFO  [main] [app](Args.java:1230) External address identified: 115.153.13.194
11:49:50.363 INFO  [main] [app](Args.java:1320) 

11:49:50.363 INFO  [main] [app](Args.java:1321) ************************ Net config ************************
11:49:50.363 INFO  [main] [app](Args.java:1322) P2P version: 11111
11:49:50.363 INFO  [main] [app](Args.java:1323) Bind IP: 172.168.1.119
11:49:50.363 INFO  [main] [app](Args.java:1324) External IP: 115.153.13.194
11:49:50.363 INFO  [main] [app](Args.java:1325) Listen port: 18888
11:49:50.363 INFO  [main] [app](Args.java:1326) Discover enable: true
11:49:50.363 INFO  [main] [app](Args.java:1327) Active node size: 0
11:49:50.363 INFO  [main] [app](Args.java:1328) Passive node size: 0
11:49:50.363 INFO  [main] [app](Args.java:1329) FastForward node size: 2
11:49:50.364 INFO  [main] [app](Args.java:1330) Seed node size: 16
11:49:50.364 INFO  [main] [app](Args.java:1331) Max connection: 30
11:49:50.364 INFO  [main] [app](Args.java:1332) Max connection with same IP: 2
11:49:50.364 INFO  [main] [app](Args.java:1333) Solidity threads: 6
11:49:50.364 INFO  [main] [app](Args.java:1334) ************************ Backup config ************************
11:49:50.364 INFO  [main] [app](Args.java:1335) Backup listen port: 10001
11:49:50.364 INFO  [main] [app](Args.java:1336) Backup member size: 0
11:49:50.364 INFO  [main] [app](Args.java:1337) Backup priority: 8
11:49:50.364 INFO  [main] [app](Args.java:1338) ************************ Code version *************************
11:49:50.364 INFO  [main] [app](Args.java:1339) Code version : 3.6.2
11:49:50.364 INFO  [main] [app](Args.java:1340) Version name: Odyssey-v3.6.1-12-g8726df803
11:49:50.364 INFO  [main] [app](Args.java:1341) Version code: 10959
11:49:50.364 INFO  [main] [app](Args.java:1342) ************************ DB config *************************
11:49:50.364 INFO  [main] [app](Args.java:1343) DB version : 2
11:49:50.364 INFO  [main] [app](Args.java:1344) DB engine : LEVELDB
11:49:50.364 INFO  [main] [app](Args.java:1345) ***************************************************************
11:49:50.365 INFO  [main] [app](Args.java:1346) 

11:49:50.365 INFO  [main] [app](FullNode.java:58) not in debug mode, it will check energy time
11:49:50.632 INFO  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:573) Refreshing org.tron.common.application.TronApplicationContext@3403e2ac: startup date [Wed Aug 14 11:49:50 CST 2019]; root of context hierarchy
11:49:56.208 INFO  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:153) JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
11:49:56.879 INFO  [main] [app](DefaultConfig.java:65) key-value data source created.
11:49:57.039 INFO  [main] [DB](DynamicPropertiesStore.java:1525) update latest block header timestamp = 0
11:49:57.040 INFO  [main] [DB](DynamicPropertiesStore.java:1533) update latest block header number = 0
11:49:57.045 INFO  [main] [DB](DynamicPropertiesStore.java:1541) update latest block header id = 00
11:49:57.046 INFO  [main] [DB](DynamicPropertiesStore.java:1546) update state flag = 0
11:49:57.079 INFO  [main] [DB](DynamicPropertiesStore.java:1646) update allow protobuf number = 0
11:49:57.294 INFO  [main] [discover](NodeManager.java:99) homeNode : Node{ host='115.153.13.194', port=18888, id=0ddcf74056db2ec6655d807dce2e719366b8477681bb261ea830e486600dff283a541564a922fdcb266f5ceeb15c40d9b110e3647732832b740f78defe0e9817}
11:49:57.294 INFO  [main] [discover](NodeManager.java:100) bootNodes : size= 16
11:49:57.426 WARN  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:544) Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountIndex' defined in URL [jar:file:/C:/Users/Administrator/Desktop/test/fullnode/FullNode.jar!/org/tron/core/db/api/index/AccountIndex.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.core.db.api.index.AccountIndex]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: sun/reflect/ConstantPool
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:275)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:834)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
	at org.tron.program.FullNode.main(FullNode.java:67)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.core.db.api.index.AccountIndex]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: sun/reflect/ConstantPool
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:267)
	... 12 common frames omitted
Caused by: java.lang.NoClassDefFoundError: sun/reflect/ConstantPool
	at net.jodah.typetools.TypeResolver.populateLambdaArgs(TypeResolver.java:311)
	at net.jodah.typetools.TypeResolver.getTypeVariableMap(TypeResolver.java:257)
	at net.jodah.typetools.TypeResolver.resolveRawClass(TypeResolver.java:239)
	at net.jodah.typetools.TypeResolver.resolveRawArguments(TypeResolver.java:176)
	at com.googlecode.cqengine.query.QueryFactory.resolveSimpleFunctionGenericTypes(QueryFactory.java:1067)
	at com.googlecode.cqengine.query.QueryFactory.attribute(QueryFactory.java:847)
	at org.tron.core.db.api.index.AccountIndex.setAttribute(AccountIndex.java:38)
	at org.tron.core.db.api.index.AbstractIndex.<init>(AbstractIndex.java:46)
	at org.tron.core.db.api.index.AccountIndex.<init>(AccountIndex.java:27)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 14 common frames omitted
Caused by: java.lang.ClassNotFoundException: sun.reflect.ConstantPool
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 28 common frames omitted
11:49:57.469 ERROR [main] [app](DefaultConfig.java:39) Uncaught exception
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountIndex' defined in URL [jar:file:/C:/Users/Administrator/Desktop/test/fullnode/FullNode.jar!/org/tron/core/db/api/index/AccountIndex.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.core.db.api.index.AccountIndex]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: sun/reflect/ConstantPool
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:275)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:834)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
	at org.tron.program.FullNode.main(FullNode.java:67)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.tron.core.db.api.index.AccountIndex]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: sun/reflect/ConstantPool
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:267)
	... 12 common frames omitted
Caused by: java.lang.NoClassDefFoundError: sun/reflect/ConstantPool
	at net.jodah.typetools.TypeResolver.populateLambdaArgs(TypeResolver.java:311)
	at net.jodah.typetools.TypeResolver.getTypeVariableMap(TypeResolver.java:257)
	at net.jodah.typetools.TypeResolver.resolveRawClass(TypeResolver.java:239)
	at net.jodah.typetools.TypeResolver.resolveRawArguments(TypeResolver.java:176)
	at com.googlecode.cqengine.query.QueryFactory.resolveSimpleFunctionGenericTypes(QueryFactory.java:1067)
	at com.googlecode.cqengine.query.QueryFactory.attribute(QueryFactory.java:847)
	at org.tron.core.db.api.index.AccountIndex.setAttribute(AccountIndex.java:38)
	at org.tron.core.db.api.index.AbstractIndex.<init>(AbstractIndex.java:46)
	at org.tron.core.db.api.index.AccountIndex.<init>(AccountIndex.java:27)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 14 common frames omitted
Caused by: java.lang.ClassNotFoundException: sun.reflect.ConstantPool
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 28 common frames omitted
11:49:58.244 INFO  [DiscoverServer] [discover](DiscoverServer.java:102) Discovery server started, bind port 18888
11:49:58.247 INFO  [nioEventLoopGroup-2-1] [discover](NodeManager.java:146) Reading Node statistics from PeersStore: 0 nodes.
11:50:58.266 INFO  [NodeManagerTasks] [discover](NodeManager.java:160) Write Node statistics to PeersStore: 613 nodes.
11:50:58.273 ERROR [NodeManagerTasks] [app](DefaultConfig.java:39) Uncaught exception
org.iq80.leveldb.DBException: Closed
	at org.fusesource.leveldbjni.internal.JniDB.put(JniDB.java:123)
	at org.fusesource.leveldbjni.internal.JniDB.put(JniDB.java:106)
	at org.tron.common.storage.leveldb.LevelDbDataSourceImpl.putData(LevelDbDataSourceImpl.java:234)
	at org.tron.common.storage.leveldb.LevelDbDataSourceImpl.putData(LevelDbDataSourceImpl.java:55)
	at org.tron.core.db.PeersStore.put(PeersStore.java:26)
	at org.tron.core.db.Manager.clearAndWriteNeighbours(Manager.java:378)
	at org.tron.common.overlay.discover.node.NodeManager.dbWrite(NodeManager.java:161)
	at org.tron.common.overlay.discover.node.NodeManager.access$100(NodeManager.java:58)
	at org.tron.common.overlay.discover.node.NodeManager$2.run(NodeManager.java:127)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

**Comment by caojianmin** [comment] 2019-08-14 04:00
@jiangyy0824 您好，另外我想问下，咱们有没有和以太坊类似的infura节点? 支持java项目访问该节点，调用trc20合约。这样我就不需要自己去创建节点了。

**Comment by jiangyy0824** [comment] 2019-08-14 04:05
@caojianmin Please use https://github.com/tronprotocol/wallet-cli, the document is here: https://tronprotocol.github.io/documentation-ZH/clients/wallet-cli/

**Comment by jiangyy0824** [comment] 2019-08-14 04:11
@caojianmin According to the error log, DB failed to initialize on your environment. We suggest you deploy fullnode on linux environment. And we will find our the root cause.

**Comment by zk19862018** [comment] 2019-08-27 02:34
Any follow up? if your problem is solved, can you close this issue?

**Closed** 2019-08-27 02:37 UTC
Labels: deployment
