### ISSUE TITLE
MongoDB event plugin not receiving topics

### ISSUE THREAD

**Issue by vahidsabet** [tronprotocol/java-tron#5370] opened 2023-07-22 08:01 UTC
Hi
Here is my configuration:

`

      vm = {
        supportConstant = true
        minTimeRatio = 0.0
        maxTimeRatio = 20.0
        saveInternalTx = true
        estimateEnergy = true
      }
      
      
      event.subscribe = {
      native = {
      useNativeQueue = false // if true, use native message queue, else use event plugin.
      bindport = 5555 // bind port
      sendqueuelength = 1000 //max length of send queue
      }
      path = "/home/event-plugin/event-plugin/build/plugins/plugin-mongodb-1.0.0.zip" // absolute path of plugin
      server = "127.0.0.1:27017" // target server address to receive event triggers
      dbconfig="eventlog|tron|123456" // dbname|username|password
      contractParse = true,
      topics = [
          {
            triggerName = "block" // block trigger, the value can't be modified
            enable = true
            topic = "block" // plugin topic, the value could be modified
          },
          {
            triggerName = "transaction"
            enable = true
            topic = "transaction"
          },
          {
            triggerName = "contractevent"
            enable = true
            topic = "contractevent"
          },
          {
            triggerName = "contractlog"
            enable = true
            topic = "contractlog"
          },
          {
            triggerName = "solidity" // solidity block event trigger, the value can't be modified
            enable = true            // the default value is true
            topic = "solidity"
          },
          {
            triggerName = "solidityevent"
            enable = false
            topic = "solidityevent"
          },
          {
            triggerName = "soliditylog"
            enable = false
            topic = "soliditylog"
          }
      ]

`

and my fullnode execute command:

nohup java -Xms20G -Xmx59G -XX:ReservedCodeCacheSize=256m
-XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m
-XX:MaxDirectMemorySize=1G -XX:+PrintGCDetails
-XX:+PrintGCDateStamps -Xloggc:gc.log
-XX:+UseConcMarkSweepGC -XX:NewRatio=2
-XX:+CMSScavengeBeforeRemark -XX:+ParallelRefProcEnabled
-XX:+HeapDumpOnOutOfMemoryError
-XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70
-jar FullNode.jar -c main_net_config.conf --es >> start.log 2>&1 &

At first I got the topics in mongoDB, but it stopped. How can I resolve this?

logs:

```
07:31:10.660 INFO  [main] [o.t.c.l.EventPluginLoader](EventPluginLoader.java:415) start loading '/home/event-plugin/event-plugin/build/plugins/plugin-mongodb-1.0.0.zip'
07:31:10.670 INFO  [main] [o.p.DefaultPluginStatusProvider](DefaultPluginStatusProvider.java:49) Enabled plugins: []
07:31:10.670 INFO  [main] [o.p.DefaultPluginStatusProvider](DefaultPluginStatusProvider.java:53) Disabled plugins: []
07:31:10.672 INFO  [main] [o.p.DefaultPluginManager](DefaultPluginManager.java:125) PF4J version 0.0.0 in 'deployment' mode
07:31:10.676 INFO  [main] [o.p.AbstractPluginManager](AbstractPluginManager.java:808) Plugin 'mongodb@1.0.0' resolved
07:31:10.677 INFO  [main] [o.p.AbstractPluginManager](AbstractPluginManager.java:327) Start plugin 'mongodb@1.0.0'
07:31:10.683 INFO  [main] [o.t.c.l.EventPluginLoader](EventPluginLoader.java:449) '/home/tron/event-plugin/event-plugin/build/plugins/plugin-mongodb-1.0.0.zip' loaded
07:31:10.860 INFO  [main] [o.m.d.cluster](SLF4JLogger.java:71) Cluster created with settings {hosts=[127.0.0.1:27017], mode=MULTIPLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=32}
07:31:10.860 INFO  [main] [o.m.d.cluster](SLF4JLogger.java:71) Adding discovered server 127.0.0.1:27017 to client view of cluster
07:31:10.922 INFO  [cluster-ClusterId{value='64bb85be266e1e1080240b74', description='null'}-127.0.0.1:27017] [o.m.d.connection](SLF4JLogger.java:71) Opened connection [connectionId{localValue:1, serverValue:4268}] to 127.0.0.1:27017
07:31:10.927 INFO  [cluster-ClusterId{value='64bb85be266e1e1080240b74', description='null'}-127.0.0.1:27017] [o.m.d.cluster](SLF4JLogger.java:71) Monitor thread successfully connected to server with description ServerDescription{address=127.0.0.1:27017, type=REPLICA_SET_PRIMARY, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 0, 4]}, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=3922202, setName='rs0', canonicalAddress=myDomain.com:27017, hosts=[myDomain:27017], passives=[], arbiters=[], primary='myDomain.com:27017', tagSet=TagSet{[]}, electionId=7fffffff0000000000000002, setVersion=1, lastWriteDate=Sat Jul 22 07:31:03 UTC 2023, lastUpdateTimeNanos=1697159965726005}
07:31:10.929 INFO  [cluster-ClusterId{value='64bb85be266e1e1080240b74', description='null'}-127.0.0.1:27017] [o.m.d.cluster](SLF4JLogger.java:71) Discovered cluster type of REPLICA_SET
07:31:10.929 INFO  [cluster-ClusterId{value='64bb85be266e1e1080240b74', description='null'}-127.0.0.1:27017] [o.m.d.cluster](SLF4JLogger.java:71) Adding discovered server myDomain.com:27017 to client view of cluster
07:31:10.930 INFO  [cluster-ClusterId{value='64bb85be266e1e1080240b74', description='null'}-127.0.0.1:27017] [o.m.d.cluster](SLF4JLogger.java:71) Server 127.0.0.1:27017 is no longer a member of the replica set.  Removing from client view of cluster.
07:31:10.931 INFO  [cluster-ClusterId{value='64bb85be266e1e1080240b74', description='null'}-127.0.0.1:27017] [o.m.d.cluster](SLF4JLogger.java:71) Canonical address myDomain.com:27017 does not match server address.  Removing 127.0.0.1:27017 from client view of cluster
07:31:10.947 INFO  [cluster-ClusterId{value='64bb85be266e1e1080240b74', description='null'}-myDomain.com:27017] [o.m.d.connection](SLF4JLogger.java:71) Opened connection [connectionId{localValue:2, serverValue:4269}] to myDomain.com:27017
07:31:10.952 INFO  [cluster-ClusterId{value='64bb85be266e1e1080240b74', description='null'}-myDomain.com:27017] [o.m.d.cluster](SLF4JLogger.java:71) Monitor thread successfully connected to server with description ServerDescription{address=myDomain:27017, type=REPLICA_SET_PRIMARY, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 0, 4]}, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=4086772, setName='rs0', canonicalAddress=myDomain.com:27017, hosts=[myDomain:27017], passives=[], arbiters=[], primary='myDomain:27017', tagSet=TagSet{[]}, electionId=7fffffff0000000000000002, setVersion=1, lastWriteDate=Sat Jul 22 07:31:03 UTC 2023, lastUpdateTimeNanos=1697159990764249}
07:31:10.952 INFO  [cluster-ClusterId{value='64bb85be266e1e1080240b74', description='null'}-myDomain.com:27017] [o.m.d.cluster](SLF4JLogger.java:71) Setting max election id to 7fffffff0000000000000002 from replica set primary myDomain:27017
07:31:10.953 INFO  [cluster-ClusterId{value='64bb85be266e1e1080240b74', description='null'}-myDomain.com:27017] [o.m.d.cluster](SLF4JLogger.java:71) Setting max set version to 1 from replica set primary myDomain:27017
07:31:10.953 INFO  [cluster-ClusterId{value='64bb85be266e1e1080240b74', description='null'}-myDomain.com:27017] [o.m.d.cluster](SLF4JLogger.java:71) Discovered replica set primary myDomain:27017
07:31:11.201 INFO  [main] [o.r.Reflections](Reflections.java:232) Reflections took 280 ms to scan 1 urls, producing 478 keys and 2749 values 
07:31:11.354 INFO  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:478) Autowired annotation is not supported on static fields: private static final java.util.concurrent.ConcurrentHashMap org.tron.core.config.args.Args.solidityContractLogTriggerMap
07:31:11.354 INFO  [main] [o.s.b.f.a.AutowiredAnnotationBeanPostProcessor](AutowiredAnnotationBeanPostProcessor.java:478) Autowired annotation is not supported on static fields: private static final java.util.concurrent.ConcurrentHashMap org.tron.core.config.args.Args.solidityContractEventTriggerMap
```

**Comment by ferdinand026** [comment] 2023-07-24 03:47
@vahidsabet The log you provided is only the part when the node starts, it shows the node loaded the plugin successfully, but it does not include the situation when the mongo stopped receiving the message. You said mongo can receive the event message initially, so you can find the last block information received by mongo, then you can try to find if there exists any error logs around that block number, and these logs help to find the root cause.

**Comment by 317787106** [comment] 2023-07-27 10:08
@vahidsabet Can you determine the first block number where you can not get topics? And find if some error logs occur. Please give the log around the block number. Is that ok after you restart the fullnode?

**Comment by vivian1912** [comment] 2023-09-14 08:51
Thanks for your contribution to Java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.

**Closed by vivian1912** 2023-09-14 08:51 UTC
Labels: topic: Event subscribe, type: Question, resolution: Needs More Information, type:docs
