### ISSUE TITLE
transfer USDT Token failed

### ISSUE THREAD

**Issue by web3-coder-hub** [tronprotocol/java-tron#5936] opened 2024-07-30 07:58 UTC
curl --request POST \
     --url https://api.trongrid.io/wallet/triggersmartcontract \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "owner_address": "TMD8Bd5EWuGBmZ8C8EiUoXxhug8Xvk8tKh",
  "contract_address": "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
  "function_selector": "transfer(address,uint256)",
  "parameter": "000000000000000000000000e1266608a11b11e6abead5de4802c1242182ddce00000000000000000000000000000000000000000000000000000000001e8480",
"fee_limit":27255900,
"call_value":0,
  "visible": true
}
'

response:
{"result":{"result":true},"transaction":{"visible":true,"txID":"f6336d84237a74b06eb5ecd190394ab9b4bb43af030c627a5ac0215f9e483249","raw_data":{"contract":[{"parameter":{"value":{"data":"a9059cbb000000000000000000000000e1266608a11b11e6abead5de4802c1242182ddce00000000000000000000000000000000000000000000000000000000001e8480","owner_address":"TMD8Bd5EWuGBmZ8C8EiUoXxhug8Xvk8tKh","contract_address":"TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"},"type_url":"type.googleapis.com/protocol.TriggerSmartContract"},"type":"TriggerSmartContract"}],"ref_block_bytes":"ef98","ref_block_hash":"3ac23f6acfc3532d","expiration":1722325962000,"fee_limit":27255900,"timestamp":1722325905529},"raw_data_hex":"0a02ef9822083ac23f6acfc3532d40909a829590325aae01081f12a9010a31747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e54726967676572536d617274436f6e747261637412740a15417b4b2f7214ffd5c501a390dc0c6131c6d2e5a887121541a614f803b6fd780986a42c78ec9c7f77e6ded13c2244a9059cbb000000000000000000000000e1266608a11b11e6abead5de4802c1242182ddce00000000000000000000000000000000000000000000000000000000001e848070f9e0fe9490329001dcc8ff0c"}}

This request is success, I got the txID, but I search in tronscan, why can't find any infomation?

**Comment by endiaoekoe** [comment] 2024-07-30 08:27
hi, @web3-coder-hub 
the response shows broadcast was successful,which  means this transaction is validated by this full node, but it doesn't mean that it can be accepted by other sr, you can find more details here https://github.com/tronprotocol/java-tron/issues/5749#issuecomment-1984991010.

**Comment by web3-coder-hub** [comment] 2024-07-30 08:38
> hi, @web3-coder-hub the response shows broadcast was successful,which means this transaction is validated by this full node, but it doesn't mean that it can be accepted by other sr, you can find more details here [#5749 (comment)](https://github.com/tronprotocol/java-tron/issues/5749#issuecomment-1984991010).

SO how can i ensure the transaction will be successful? I just need transfer token and transaction  must be success.

**Comment by endiaoekoe** [comment] 2024-07-30 09:02
> > hi, @web3-coder-hub the response shows broadcast was successful,which means this transaction is validated by this full node, but it doesn't mean that it can be accepted by other sr, you can find more details here [#5749 (comment)](https://github.com/tronprotocol/java-tron/issues/5749#issuecomment-1984991010).
> 
> SO how can i ensure the transaction will be successful? I just need transfer token and transaction must be success.

When transferring TRC20 assets (e.g. USDT) on the TRON network, there are several things to consider to ensure that the transaction is broadcasted and successfully on chain:

- Sufficient TRX balance:
Ensure that the sending account has enough TRX to cover the transaction fees (energy consumption).
If the TRX balance is insufficient, the transaction may fail or not be broadcast.

- Correct transaction construction:
Ensure that the transaction parameters are correct, including the receiving address, transfer amount, contract address, etc.

- Transaction Prioritization:
Error handling and retry mechanism:
Implement error handling logic to handle transactions appropriately when they fail.
Consider implementing a retry mechanism that automatically rebroadcasts the transaction if it is not confirmed.

- Avoid duplicate transactions:
Check the status of the original transaction before rebroadcasting it.

- Network Status Monitoring:
Monitor the overall status of the TRON network to avoid sending important transactions when the network is congested.
For critical transactions, consider using a higher energy limit to increase the priority.For critical transactions, consider using a higher energy limit to increase the priority.

**Comment by web3-coder-hub** [comment] 2024-07-30 09:11
> > > hi, @web3-coder-hub the response shows broadcast was successful,which means this transaction is validated by this full node, but it doesn't mean that it can be accepted by other sr, you can find more details here [#5749 (comment)](https://github.com/tronprotocol/java-tron/issues/5749#issuecomment-1984991010).
> > 
> > 
> > SO how can i ensure the transaction will be successful? I just need transfer token and transaction must be success.
> 
> When transferring TRC20 assets (e.g. USDT) on the TRON network, there are several things to consider to ensure that the transaction is broadcasted and successfully on chain:
> 
> * Sufficient TRX balance:
>   Ensure that the sending account has enough TRX to cover the transaction fees (energy consumption).
>   If the TRX balance is insufficient, the transaction may fail or not be broadcast.
> * Correct transaction construction:
>   Ensure that the transaction parameters are correct, including the receiving address, transfer amount, contract address, etc.
> * Error handling and retry mechanism:
>   Implement error handling logic to handle transactions appropriately when they fail.
>   Consider implementing a retry mechanism that automatically rebroadcasts the transaction if it is not confirmed.
> * Avoid duplicate transactions:
>   Check the status of the original transaction before rebroadcasting it.
> * Network Status Monitoring:
>   Monitor the overall status of the TRON network to avoid sending important transactions when the network is congested.
>   For critical transactions, consider using a higher energy limit to increase the priority.For critical transactions, consider using a higher energy limit to increase the priority.

OK, I signed the transaction and request this api "wallet/broadcasttransaction", but I got a result :class java.lang.NullPointerException : null.
![WeChat35e216fb49ce38f1d092928bb1777f8a](https://github.com/user-attachments/assets/ece60091-3700-4fc9-929a-88f90fc63ef2)

**Comment by endiaoekoe** [comment] 2024-07-31 03:40
@web3-coder-hub 
from the error pic you provided,there are some possible root causes,as below: 
a. Incomplete or incorrectly formatted transaction object
b. Invalid or missing signature
c. Misconfiguration of the API endpoint
d. Temporary server-side failure
e. Network connection problem

Check Steps: 
a. Check the transaction object:
Ensure that all required fields are filled in correctly (e.g. from, to, amount, contract address, etc.)
Verify that all numeric type fields (e.g., amount) are set correctly.
b. Verify signatures:
Ensure that the correct private key has been used for signing
Check that the signing process is performed correctly
c. Verify API calls:
Ensure that the correct API endpoint URL is used
Check that the request header and request body format are correct.
d. Retry mechanism:
Implement a simple retry mechanism to retry later if an error is encountered.
e. Use more detailed error handling:
Catch specific types of exceptions to get more information about the error.

**Comment by endiaoekoe** [comment] 2024-07-31 03:45
@web3-coder-hub 
by the way, does the NullPointerException occur your local client side(your code)or is it just returned by the response from the server side?

**Comment by web3-coder-hub** [comment] 2024-08-01 07:26
> from the server side

from the server side, I solved this issue, but throw another error:  but it is not contained of permission.

**Comment by halibobo1205** [comment] 2024-08-01 08:49
`triggersmartcontract` is used to create a transaction, and then sign the transaction by the private key,   The final call `broadcasttransaction` broadcasts the signed transaction and waits for confirmation.

**Comment by 0xbigapple** [comment] 2024-08-01 13:37
I have written a demo ，and hope it can be helpful for you.

```
const TronWeb = require('tronweb');
const axios = require('axios');

// TronGrid API endpoint
const API_URL = "https://api.trongrid.io";

// Your account details
const ACCOUNT_ADDRESS = "";
const PRIVATE_KEY = "";

// Smart contract details
const CONTRACT_ADDRESS = "";
const TO_ADDRESS = "";
const AMOUNT = 1;  // Amount

// Initialize TronWeb
const tronWeb = new TronWeb({
    fullHost: 'https://api.trongrid.io',
    headers: {"TRON-PRO-API-KEY": ''}, 
    privateKey: PRIVATE_KEY
})

async function main() {
    try {
        // Step 1: Trigger smart contract
        console.log("Triggering smart contract...");
        const transaction = await tronWeb.transactionBuilder.triggerSmartContract(
            tronWeb.address.toHex(CONTRACT_ADDRESS),
            "transfer(address,uint256)",
            {},
            [
                {type: 'address', value: tronWeb.address.toHex(TO_ADDRESS)},
                {type: 'uint256', value: tronWeb.toHex(AMOUNT)}
            ],
            tronWeb.address.toHex(ACCOUNT_ADDRESS)
        );

        if (!transaction.result || !transaction.result.result) {
            throw new Error(`Failed to trigger smart contract: ${JSON.stringify(transaction)}`);
        }
        console.log("transaction Response:", transaction);

        // Step 2: Sign the transaction
        console.log("Signing transaction...");
        const signedTransaction = await tronWeb.trx.sign(transaction.transaction);
        console.log("signedTransaction Response:", signedTransaction);

        // Step 3: Broadcast the signed transaction
        console.log("Broadcasting transaction...");
        const broadcastResponse = await axios.post(`${API_URL}/wallet/broadcasttransaction`, signedTransaction);

        console.log("Broadcast response:", broadcastResponse);
        console.log("Transaction complete.");
    } catch (error) {
        console.error("Error:", error);
    }
}

main();

```

**Closed** 2024-08-02 09:00 UTC
Labels: type:docs

**Comment by web3-coder-hub** [comment] 2024-08-02 09:02
@halibobo1205 @0xbigapple Ok,thanks!
