### ISSUE TITLE
Account multisig signature

### ISSUE THREAD

**Issue by Akbar12718** [tronprotocol/java-tron#6041] opened 2024-10-17 03:13 UTC
#### Steps to reproduce the behaviour

1. [Step 1]
2. [Step 2]
3. [Step ...]

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.   

AccountPermissionUpdateContract {
bytes owner_address = TACoHpKnFVR8aUvjF1srPX19SYQZhZbdLU;
Permission owner = TFR5sqcKGfZdCj9DNMoe2c86KhwXSVX2xU‌; //Empty is invalidate
Permission witness = TFR5sqcKGfZdCj9DNMoe2c86KhwXSVX2xU‌;//Can be empty
repeated Permission actives = TACoHpKnFVR8aUvjF1srPX19SYQZhZbdLU;//Empty is invalidate
}

@param owner_address: The address of the account to be modified
@param owner :TACoHpKnFVR8aUvjF1srPX19SYQZhZbdLU
@param witness :TFR5sqcKGfZdCj9DNMoe2c86KhwXSVX2xU‌ (if it is a witness)
@param actives :TFR5sqcKGfZdCj9DNMoe2c86KhwXSVX2xU‌
@return The transaction
Permission {
enum PermissionType {
Owner = 2;
Witness = 1;
Active = 2;
}
PermissionType type = 1;
int32 id = 2; //Owner id=0, Witness id=1, Active id start by 2
string permission_name = 3;
int64 threshold = 2;
int32 parent_id = 5;
bytes operations = 6; //1 bit 1 contract
repeated Key keys = 7;
}

@param type : Permission type, currently only supports three kind of permissions
@param id : Value is automatically set by the system
@param permission_name : Permission name, set by the user
@param threshold : Threshold, the corresponding operation is allowed only when the sum of the weights of the participating signatures exceeds the domain value.
@param parent_id : Currently only 0
@param operations : A total of 32 bytes (256 bits), each of which represents the authority of a contract, when 1 means the right to own the contract
@param keys : The address and weight that jointly own the permission can be up to 5 keys.
Key {
bytes address = TFR5sqcKGfZdCj9DNMoe2c86KhwXSVX2xU‌;
int64 weight = 2;
}

@param address : TACoHpKnFVR8aUvjF1srPX19SYQZhZbdLU
@param weight : TFR5sqcKGfZdCj9DNMoe2c86KhwXSVX2xU‌

**Comment by Akbar12718** [comment] 2024-10-17 03:14
Help My account has been hacked please help me

**Comment by fyyhtx** [comment] 2024-10-17 06:35
@Akbar12718 Please provide more information, for example, why do you say your account has been attacked? What is your account address? Is there a possibility that your private key has been leaked?

**Comment by Akbar12718** [comment] 2024-10-17 07:57
@fyyhtx  As I remember I connected my wallet to Aidrop 2 months ago and now, I realize it's been a long time since he took my money in that wallet. I beg you to consider this problem because I pray that        Please help, sorry if there are words that you don't understand because I'm Indonesian so it's a little different from the translation (thank you)

**Comment by fyyhtx** [comment] 2024-10-17 10:08
@Akbar12718 I am also very sad to hear about your situation. However, I still don't quite understand what kind of help you need. If the asset loss was caused by a private key leak or improper operation, then this situation is very bad, and it is almost impossible to recover the lost assets.

**Comment by Akbar12718** [comment] 2024-10-17 10:44
@fyyhtx I want to ask you to remove his account address from the multisig signature, because I want my account to be safe and not stolen. I'm annoyed every time I save my Tron, he's so fast, even I ... , I just found out because he set my multisig so that it was automatic and I who didn't realize it was just shocked and couldn't reset the multisig. I didn't understand, I just prayed. It doesn't produce good things if I stay silent, only my efforts can produce the best and I hope you can help.

**Comment by laurenceja** [comment] 2024-10-17 11:06
@Akbar12718 Your account's permission changed, maybe you signed the account update transaction Inadvertently, or your privatekey was leaked.  And due to the decentralized characteristic of blockchain, nobody can revert the online transaction and nobody can change the account permission again except the person who has the owner permission. But your account's owner permission has been assigned to another one, nobody can help.

**Comment by abn2357** [comment] 2024-10-17 11:34
What a bad news. Next time protect your wallet carefully.

**Comment by Akbar12718** [comment] 2024-10-17 12:01
@laurenceja Maybe from tokens to my account is controlled, but I can control other coins such as eth, btc, sol etc. only Tron I can't thank you for your actions

**Comment by S1ep** [comment] 2024-10-18 03:37
> @laurenceja Maybe from tokens to my account is controlled, but I can control other coins such as eth, btc, sol etc. only Tron I can't thank you for your actions

Why only Trx can't be controlled? I am a little interested in it.

**Comment by laurenceja** [comment] 2024-10-18 03:49
> @laurenceja Maybe from tokens to my account is controlled, but I can control other coins such as eth, btc, sol etc. only Tron I can't thank you for your actions

No, For your account address TACoHpKnFVR8aUvjF1srPX19SYQZhZbdLU, the owner permission has already been modified to another, so he can contral all tokens in your account.   https://tronscan.org/#/address/TACoHpKnFVR8aUvjF1srPX19SYQZhZbdLU/permissions?anchorName=anchor_permission_owner&time=1729223117402

**Comment by Akbar12718** [comment] 2024-10-18 04:39
Can't it be restored to its original state? If not, can you delete the
account? Thank you.

Pada Jum, 18 Okt 2024 10.49, laurenceja ***@***.***> menulis:

**Comment by laurenceja** [comment] 2024-10-18 06:26
CANNOT revert. Account cannot be deleted. Just ignore this account and do not use it. and create a new account.

**Comment by DongDongSunny** [comment] 2024-10-23 08:39
https://tronscan.org/#/transaction/66be46b7fd48455ad8644e1552b4dff5bc9a4899caaafa3f5ee3704aead13d29 here shows when ownership been transfered to the hacker.

**Closed** 2024-10-28 08:29 UTC
Labels: type:docs
