### ISSUE TITLE
All peer nodes of the running node are unavailable

### ISSUE THREAD

**Issue by shixiaofeia** [tronprotocol/java-tron#3876] opened 2021-06-25 06:57 UTC
### 1. What did you do?

I'm running full node synchronization, but the peer node can't connect

### 2. What did you expect to see?

Expect to see the nodes sync normally

### 3. What did you see instead?

My configuration file is  https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf

tail -n 500 tron.log |grep reason
```
reason: TOO_MANY_PEERS
reason: TOO_MANY_PEERS
reason: TIME_OUT
reason: TOO_MANY_PEERS
reason: TOO_MANY_PEERS
reason: TOO_MANY_PEERS
reason: TOO_MANY_PEERS
reason: TOO_MANY_PEERS
```

All peer nodes are unavailable
```
============ Peer stats: all 9, active 9, passive 0

Peer 47.75.249.119:18888 [71a3dbb2]
ping msg: count 1, max-average-min-last: 16 16 16 16
connect time: 19s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:31354973
syncBlockRequestedSize:0
remainNum:18622
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 247(59), discover: 1/1 0/0 12/12 0/0 43ms, p2p: 1/1/3 , tron: 5/7 X 2 =>TOO_MANY_PEERS, tcp flow: 164096

Peer 161.117.239.250:18888 [32e32daf]
ping msg: count 1, max-average-min-last: 50 50 50 50
connect time: 26s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:31354973
syncBlockRequestedSize:0
remainNum:18619
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 246(0), discover: 1/1 0/0 4/4 0/0 50ms, p2p: 1/1/2 , tron: 5/6 X 1 =>TOO_MANY_PEERS, tcp flow: 164096

Peer 161.117.224.116:18888 [ed50bb3e]
ping msg: count 3, max-average-min-last: 58 55 54 58
connect time: 26s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:31354973
syncBlockRequestedSize:0
remainNum:18619
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 246(0), discover: 1/1 0/0 0/0 0/0 60ms, p2p: 2/2/2 , tron: 12/12 X 1<=TIME_OUT , tcp flow: 328196

Peer 12.203.154.36:18888 [d4ec05a1]
ping msg: count 3, max-average-min-last: 300 190 134 136
connect time: 8s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:31354973
syncBlockRequestedSize:0
remainNum:18625
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 237(54), discover: 1/1 0/0 23/23 0/0 130ms, p2p: 3/3/3 , tron: 574/21 X 2<=TIME_OUT , tcp flow: 35972641

Peer 192.111.146.14:18888 [e6295591]
ping msg: count 3, max-average-min-last: 194 192 191 191
connect time: 15s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:31354973
syncBlockRequestedSize:0
remainNum:17704
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 236(58), discover: 1/1 0/0 0/0 0/0 193ms, p2p: 3/3/3 , tron: 112/16 X 2<=TIME_OUT , tcp flow: 6660542

Peer 47.254.71.253:18888 [35728771]
ping msg: count 2, max-average-min-last: 489 318 148 148
connect time: 11s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:31354973
syncBlockRequestedSize:0
remainNum:18624
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 237(54), discover: 1/1 0/0 5/5 0/0 139ms, p2p: 2/2/3 , tron: 556/18 X 2<=TIME_OUT=>TOO_MANY_PEERS, tcp flow: 36114994

Peer 47.90.244.251:18888 [ebac4bac]
ping msg: count 4, max-average-min-last: 1931 618 179 179
connect time: 15s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:31354973
syncBlockRequestedSize:0
remainNum:18623
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 236(58), discover: 1/1 0/0 23/23 0/0 178ms, p2p: 3/3/3 , tron: 517/22 X 2<=TIME_OUT , tcp flow: 33020784

Peer 47.252.17.26:18888 [58398cb3]
ping msg: count 4, max-average-min-last: 2205 688 179 181
connect time: 15s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:31354973
syncBlockRequestedSize:0
remainNum:18623
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 236(57), discover: 1/1 0/0 12/12 0/0 179ms, p2p: 3/3/3 , tron: 517/22 X 2<=TIME_OUT , tcp flow: 33028694

Peer 185.44.66.101:18888 [3226d590]
ping msg: count 4, max-average-min-last: 2397 747 194 194
connect time: 15s
last know block num: 0
needSyncFromPeer:true
needSyncFromUs:false
syncToFetchSize:4000
syncToFetchSizePeekNum:31354973
syncBlockRequestedSize:0
remainNum:18623
syncChainRequested:0
blockInProcess:0
NodeStat[reput: 236(57), discover: 1/1 0/0 5/5 6/6 191ms, p2p: 3/3/3 , tron: 506/22 X 2<=TIME_OUT , tcp flow: 32649670


06:55:29.991 INFO  [qtp390177332-160] [o.e.j.s.ConnectionLimit](ConnectionLimit.java:144) Connection Limit(50) cleared for [ServerConnector@19e53781{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}]
06:55:29.992 INFO  [qtp390177332-340] [o.e.j.s.ConnectionLimit](ConnectionLimit.java:130) Connection Limit(50) reached for [ServerConnector@19e53781{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}]
06:55:33.815 INFO  [qtp390177332-340] [o.e.j.s.ConnectionLimit](ConnectionLimit.java:144) Connection Limit(50) cleared for [ServerConnector@19e53781{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}]
06:55:33.816 INFO  [qtp390177332-358] [o.e.j.s.ConnectionLimit](ConnectionLimit.java:130) Connection Limit(50) reached for [ServerConnector@19e53781{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}]
06:55:35.153 INFO  [qtp390177332-340] [o.e.j.s.ConnectionLimit](ConnectionLimit.java:144) Connection Limit(50) cleared for [ServerConnector@19e53781{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}]
06:55:35.153 INFO  [qtp390177332-358] [o.e.j.s.ConnectionLimit](ConnectionLimit.java:130) Connection Limit(50) reached for [ServerConnector@19e53781{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}]
06:55:35.273 WARN  [pool-50-thread-1] [net](PeerStatusCheck.java:49) Peer /161.117.239.250 not sync for a long time.
06:55:35.273 INFO  [pool-50-thread-1] [net](Channel.java:129) Send to /161.117.239.250:18888 online-time 31s, type: P2P_DISCONNECT
reason: TIME_OUT
06:55:35.274 WARN  [pool-50-thread-1] [net](PeerStatusCheck.java:49) Peer /161.117.224.116 not sync for a long time.
06:55:35.274 INFO  [pool-50-thread-1] [net](Channel.java:129) Send to /161.117.224.116:18888 online-time 31s, type: P2P_DISCONNECT
reason: TIME_OUT
06:55:35.278 INFO  [TronJClientWorker-1] [net](TronChannelInitializer.java:48) Close channel:/161.117.224.116:18888 | ed50bb3ee4353b4bc5aa161daec36ece74a1d93c294caa42b9648c1c52ecd3a02df74c755ea40904cad54a645939b9dbf4e5a5092535a81ec0ab26f551a98765
06:55:35.279 INFO  [TronJClientWorker-2] [net](TronChannelInitializer.java:48) Close channel:/161.117.239.250:18888 | 32e32daf6ac7cd9f8980f8cbd5485f8665f1d1cd7d24d791845d863c21f67db7d7ead55f9bb73e42b081ff8a81acb912231651de9609875c7f7c8f0eeb4b4470
06:55:35.306 INFO  [qtp390177332-340] [o.e.j.s.ConnectionLimit](ConnectionLimit.java:144) Connection Limit(50) cleared for [ServerConnector@19e53781{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}]
06:55:35.312 INFO  [qtp390177332-358] [o.e.j.s.ConnectionLimit](ConnectionLimit.java:130) Connection Limit(50) reached for [ServerConnector@19e53781{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}]
06:55:35.967 INFO  [qtp390177332-340] [o.e.j.s.ConnectionLimit](ConnectionLimit.java:144) Connection Limit(50) cleared for [ServerConnector@19e53781{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}]

```

**Comment by Benson0224** [comment] 2021-06-25 07:05
Please provide the full log file for further investigation. 
The log fragment in this issue has no valid information.

**Comment by shixiaofeia** [comment] 2021-06-25 07:15
[Uploading tron.zip…]()

**Comment by shixiaofeia** [comment] 2021-06-25 07:16
> 请提供完整的日志文件以供进一步调查。
> 此问题中的日志片段没有有效信息。

[tron.zip](https://github.com/tronprotocol/java-tron/files/6714274/tron.zip)

**Comment by Benson0224** [comment] 2021-06-25 07:22
hi, Please check this guide:  https://cn.developers.tron.network/docs/faq#8%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%E8%8A%82%E7%82%B9%E5%8C%BA%E5%9D%97%E5%90%8C%E6%AD%A5%E6%85%A2%E6%88%96%E8%80%85%E5%81%9C%E6%AD%A2%E5%90%8C%E6%AD%A5%E9%97%AE%E9%A2%98%EF%BC%9F

change the `maxTimeRatio` in configuration file and re-start the node. 

![image](https://user-images.githubusercontent.com/61768920/123386267-0db46100-d5c9-11eb-91a5-1e07504ebb21.png)

**Comment by shixiaofeia** [comment] 2021-06-25 07:24
Okay, thank you, I will try to modify this configuration first

**Comment by pthor11** [comment] 2021-06-25 07:25
@Benson0224 How to increase retry in case full node is stalled ?

**Comment by Benson0224** [comment] 2021-06-25 07:28
> @Benson0224 How to increase retry in case full node is stalled ?

Currently no such configuration. Stop synchronization needs to be handled according to the error message case by case.

**Comment by pthor11** [comment] 2021-06-25 07:53
@Benson0224 : does increase maxActiveNodes and decrease minParticipationRate would solve this kind of timeout connection problem ?

**Comment by Benson0224** [comment] 2021-06-25 08:13
> @Benson0224 : does increase maxActiveNodes and decrease minParticipationRate would solve this kind of timeout connection problem ?

as mentioned above, synchronization issues need to be handled case by case. The `TIME_OUT` here is just an `INFO` after the node failed. it is not the real reason of failure.

For this case, the real reason for this failure is "Different resultCode". usually, it is caused by HW configuration is different compares to the SR node. it can be fixed by increase the `maxTimeRatio`. 

![image](https://user-images.githubusercontent.com/61768920/123391710-e1034800-d5ce-11eb-90d4-5175945479ac.png)

**Comment by pthor11** [comment] 2021-06-25 08:26
Thank you @Benson0224 , it clears me out a lot.

**Closed** 2021-06-28 04:11 UTC

**Comment by chandramouli-scs** [comment] 2021-06-30 04:45
> ### 1. What did you do?
> I'm running full node synchronization, but the peer node can't connect
> 
> ### 2. What did you expect to see?
> Expect to see the nodes sync normally
> 
> ### 3. What did you see instead?
> My configuration file is https://github.com/tronprotocol/tron-deployment/blob/master/main_net_config.conf
> 
> tail -n 500 tron.log |grep reason
> 
> ```
> reason: TOO_MANY_PEERS
> reason: TOO_MANY_PEERS
> reason: TIME_OUT
> reason: TOO_MANY_PEERS
> reason: TOO_MANY_PEERS
> reason: TOO_MANY_PEERS
> reason: TOO_MANY_PEERS
> reason: TOO_MANY_PEERS
> ```
> 
> All peer nodes are unavailable
> 
> ```
> ============ Peer stats: all 9, active 9, passive 0
> 
> Peer 47.75.249.119:18888 [71a3dbb2]
> ping msg: count 1, max-average-min-last: 16 16 16 16
> connect time: 19s
> last know block num: 0
> needSyncFromPeer:true
> needSyncFromUs:false
> syncToFetchSize:4000
> syncToFetchSizePeekNum:31354973
> syncBlockRequestedSize:0
> remainNum:18622
> syncChainRequested:0
> blockInProcess:0
> NodeStat[reput: 247(59), discover: 1/1 0/0 12/12 0/0 43ms, p2p: 1/1/3 , tron: 5/7 X 2 =>TOO_MANY_PEERS, tcp flow: 164096
> 
> Peer 161.117.239.250:18888 [32e32daf]
> ping msg: count 1, max-average-min-last: 50 50 50 50
> connect time: 26s
> last know block num: 0
> needSyncFromPeer:true
> needSyncFromUs:false
> syncToFetchSize:4000
> syncToFetchSizePeekNum:31354973
> syncBlockRequestedSize:0
> remainNum:18619
> syncChainRequested:0
> blockInProcess:0
> NodeStat[reput: 246(0), discover: 1/1 0/0 4/4 0/0 50ms, p2p: 1/1/2 , tron: 5/6 X 1 =>TOO_MANY_PEERS, tcp flow: 164096
> 
> Peer 161.117.224.116:18888 [ed50bb3e]
> ping msg: count 3, max-average-min-last: 58 55 54 58
> connect time: 26s
> last know block num: 0
> needSyncFromPeer:true
> needSyncFromUs:false
> syncToFetchSize:4000
> syncToFetchSizePeekNum:31354973
> syncBlockRequestedSize:0
> remainNum:18619
> syncChainRequested:0
> blockInProcess:0
> NodeStat[reput: 246(0), discover: 1/1 0/0 0/0 0/0 60ms, p2p: 2/2/2 , tron: 12/12 X 1<=TIME_OUT , tcp flow: 328196
> 
> Peer 12.203.154.36:18888 [d4ec05a1]
> ping msg: count 3, max-average-min-last: 300 190 134 136
> connect time: 8s
> last know block num: 0
> needSyncFromPeer:true
> needSyncFromUs:false
> syncToFetchSize:4000
> syncToFetchSizePeekNum:31354973
> syncBlockRequestedSize:0
> remainNum:18625
> syncChainRequested:0
> blockInProcess:0
> NodeStat[reput: 237(54), discover: 1/1 0/0 23/23 0/0 130ms, p2p: 3/3/3 , tron: 574/21 X 2<=TIME_OUT , tcp flow: 35972641
> 
> Peer 192.111.146.14:18888 [e6295591]
> ping msg: count 3, max-average-min-last: 194 192 191 191
> connect time: 15s
> last know block num: 0
> needSyncFromPeer:true
> needSyncFromUs:false
> syncToFetchSize:4000
> syncToFetchSizePeekNum:31354973
> syncBlockRequestedSize:0
> remainNum:17704
> syncChainRequested:0
> blockInProcess:0
> NodeStat[reput: 236(58), discover: 1/1 0/0 0/0 0/0 193ms, p2p: 3/3/3 , tron: 112/16 X 2<=TIME_OUT , tcp flow: 6660542
> 
> Peer 47.254.71.253:18888 [35728771]
> ping msg: count 2, max-average-min-last: 489 318 148 148
> connect time: 11s
> last know block num: 0
> needSyncFromPeer:true
> needSyncFromUs:false
> syncToFetchSize:4000
> syncToFetchSizePeekNum:31354973
> syncBlockRequestedSize:0
> remainNum:18624
> syncChainRequested:0
> blockInProcess:0
> NodeStat[reput: 237(54), discover: 1/1 0/0 5/5 0/0 139ms, p2p: 2/2/3 , tron: 556/18 X 2<=TIME_OUT=>TOO_MANY_PEERS, tcp flow: 36114994
> 
> Peer 47.90.244.251:18888 [ebac4bac]
> ping msg: count 4, max-average-min-last: 1931 618 179 179
> connect time: 15s
> last know block num: 0
> needSyncFromPeer:true
> needSyncFromUs:false
> syncToFetchSize:4000
> syncToFetchSizePeekNum:31354973
> syncBlockRequestedSize:0
> remainNum:18623
> syncChainRequested:0
> blockInProcess:0
> NodeStat[reput: 236(58), discover: 1/1 0/0 23/23 0/0 178ms, p2p: 3/3/3 , tron: 517/22 X 2<=TIME_OUT , tcp flow: 33020784
> 
> Peer 47.252.17.26:18888 [58398cb3]
> ping msg: count 4, max-average-min-last: 2205 688 179 181
> connect time: 15s
> last know block num: 0
> needSyncFromPeer:true
> needSyncFromUs:false
> syncToFetchSize:4000
> syncToFetchSizePeekNum:31354973
> syncBlockRequestedSize:0
> remainNum:18623
> syncChainRequested:0
> blockInProcess:0
> NodeStat[reput: 236(57), discover: 1/1 0/0 12/12 0/0 179ms, p2p: 3/3/3 , tron: 517/22 X 2<=TIME_OUT , tcp flow: 33028694
> 
> Peer 185.44.66.101:18888 [3226d590]
> ping msg: count 4, max-average-min-last: 2397 747 194 194
> connect time: 15s
> last know block num: 0
> needSyncFromPeer:true
> needSyncFromUs:false
> syncToFetchSize:4000
> syncToFetchSizePeekNum:31354973
> syncBlockRequestedSize:0
> remainNum:18623
> syncChainRequested:0
> blockInProcess:0
> NodeStat[reput: 236(57), discover: 1/1 0/0 5/5 6/6 191ms, p2p: 3/3/3 , tron: 506/22 X 2<=TIME_OUT , tcp flow: 32649670
> 
> 
> 06:55:29.991 INFO  [qtp390177332-160] [o.e.j.s.ConnectionLimit](ConnectionLimit.java:144) Connection Limit(50) cleared for [ServerConnector@19e53781{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}]
> 06:55:29.992 INFO  [qtp390177332-340] [o.e.j.s.ConnectionLimit](ConnectionLimit.java:130) Connection Limit(50) reached for [ServerConnector@19e53781{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}]
> 06:55:33.815 INFO  [qtp390177332-340] [o.e.j.s.ConnectionLimit](ConnectionLimit.java:144) Connection Limit(50) cleared for [ServerConnector@19e53781{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}]
> 06:55:33.816 INFO  [qtp390177332-358] [o.e.j.s.ConnectionLimit](ConnectionLimit.java:130) Connection Limit(50) reached for [ServerConnector@19e53781{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}]
> 06:55:35.153 INFO  [qtp390177332-340] [o.e.j.s.ConnectionLimit](ConnectionLimit.java:144) Connection Limit(50) cleared for [ServerConnector@19e53781{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}]
> 06:55:35.153 INFO  [qtp390177332-358] [o.e.j.s.ConnectionLimit](ConnectionLimit.java:130) Connection Limit(50) reached for [ServerConnector@19e53781{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}]
> 06:55:35.273 WARN  [pool-50-thread-1] [net](PeerStatusCheck.java:49) Peer /161.117.239.250 not sync for a long time.
> 06:55:35.273 INFO  [pool-50-thread-1] [net](Channel.java:129) Send to /161.117.239.250:18888 online-time 31s, type: P2P_DISCONNECT
> reason: TIME_OUT
> 06:55:35.274 WARN  [pool-50-thread-1] [net](PeerStatusCheck.java:49) Peer /161.117.224.116 not sync for a long time.
> 06:55:35.274 INFO  [pool-50-thread-1] [net](Channel.java:129) Send to /161.117.224.116:18888 online-time 31s, type: P2P_DISCONNECT
> reason: TIME_OUT
> 06:55:35.278 INFO  [TronJClientWorker-1] [net](TronChannelInitializer.java:48) Close channel:/161.117.224.116:18888 | ed50bb3ee4353b4bc5aa161daec36ece74a1d93c294caa42b9648c1c52ecd3a02df74c755ea40904cad54a645939b9dbf4e5a5092535a81ec0ab26f551a98765
> 06:55:35.279 INFO  [TronJClientWorker-2] [net](TronChannelInitializer.java:48) Close channel:/161.117.239.250:18888 | 32e32daf6ac7cd9f8980f8cbd5485f8665f1d1cd7d24d791845d863c21f67db7d7ead55f9bb73e42b081ff8a81acb912231651de9609875c7f7c8f0eeb4b4470
> 06:55:35.306 INFO  [qtp390177332-340] [o.e.j.s.ConnectionLimit](ConnectionLimit.java:144) Connection Limit(50) cleared for [ServerConnector@19e53781{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}]
> 06:55:35.312 INFO  [qtp390177332-358] [o.e.j.s.ConnectionLimit](ConnectionLimit.java:130) Connection Limit(50) reached for [ServerConnector@19e53781{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}]
> 06:55:35.967 INFO  [qtp390177332-340] [o.e.j.s.ConnectionLimit](ConnectionLimit.java:144) Connection Limit(50) cleared for [ServerConnector@19e53781{HTTP/1.1,[http/1.1]}{0.0.0.0:8091}]
> ```

Please help i also got same errors ,  i have changed maxTimeRatio to 20.0 but no use , Thank you

**Comment by Benson0224** [comment] 2021-06-30 05:00
> Please help i also got same errors , i have changed maxTimeRatio to 20.0 but no use , Thank you

Can you share the HW configuration of your server, the recommended HW configuration is 16core 32GRAM 1T ssd.

if you still see the "Different result code" error,  you can change `maxTimeRatio ` to 50 or even higher and restart the node. thanks.

**Comment by shixiaofeia** [comment] 2021-07-01 04:18
I modified the maxTimeRatio to 30, and I allocated 32G of memory for the program to run
